-- Test-only baseline for SANAD ERP cloud replica/read-model contracts.
-- Never apply to production.

create extension if not exists pgcrypto;

create schema if not exists private;

create table public.business_profiles (
  id uuid primary key,
  owner_user_id uuid not null
);

create table public.business_team_members (
  business_id uuid not null,
  user_id uuid not null,
  status text not null
);

create table public.business_erp_baseline_runs (
  id uuid primary key default gen_random_uuid(),
  baseline_public_id uuid not null unique,
  business_id uuid not null,
  source_instance_id uuid,
  bridge_device_id uuid,
  connection_id uuid,
  location_id uuid,
  baseline_kind text not null,
  adapter_code text default 'edaa_v5',
  adapter_version text default 'v1',
  schema_fingerprint text default 'test',
  status text not null,
  manifest jsonb not null default '{}'::jsonb,
  expected_counts jsonb not null default '{}'::jsonb,
  received_counts jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  last_seen_at timestamptz not null default now(),
  error_code text,
  error_detail text
);

create table public.business_erp_snapshot_rows (
  id bigint generated by default as identity primary key,
  snapshot_public_id uuid not null,
  business_id uuid not null,
  source_instance_id uuid,
  table_name text not null,
  row_key text not null,
  row_hash text not null,
  row_data jsonb not null,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(snapshot_public_id,table_name,row_key)
);

create table public.business_erp_raw_events (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null,
  source_instance_id uuid,
  entity_type text not null,
  integrity jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

create table public.ai_financial_context_access_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  scope_kind text not null,
  business_id uuid,
  period_from date not null,
  period_to date not null,
  result_contract_version integer not null,
  purpose text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function private.user_is_business_owner(p_business_id uuid,p_user_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$
  select exists(select 1 from public.business_profiles b where b.id=p_business_id and b.owner_user_id=p_user_id);
$$;

create or replace function private.user_is_active_business_member(p_business_id uuid,p_user_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$
  select exists(select 1 from public.business_team_members m where m.business_id=p_business_id and m.user_id=p_user_id and m.status='active');
$$;

create or replace function public.can_access_business_financial_v1(p_business_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$
  select private.user_is_business_owner(p_business_id,auth.uid())
      or private.user_is_active_business_member(p_business_id,auth.uid());
$$;

create or replace function public.get_business_erp_snapshot_status_v1(p_business_id uuid)
returns jsonb language sql security definer set search_path=''
as $$
  select coalesce((
    select jsonb_build_object(
      'available',status='completed',
      'snapshot_public_id',baseline_public_id,
      'status',status,
      'completed_at',completed_at,
      'received_counts',received_counts,
      'manifest',manifest,
      'contract_version',1
    )
    from public.business_erp_baseline_runs
    where business_id=p_business_id and baseline_kind='logical_backup'
    order by completed_at desc nulls last,started_at desc
    limit 1
  ),jsonb_build_object('available',false,'status','not_started','contract_version',1));
$$;

grant usage on schema public to authenticated;
grant usage on schema private to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant execute on all functions in schema public to authenticated;
grant execute on all functions in schema private to authenticated;
