from pathlib import Path

path = Path('src/features/operations/OperationDetailsRuntimeV2.tsx')
source = path.read_text(encoding='utf-8')

replacements = [
    (
        "const ANALYSIS_POLL_MS = 3500;",
        "const ANALYSIS_POLL_MS = 3500;\nconst MIN_PREVIEW_ZOOM = 1;\nconst MAX_PREVIEW_ZOOM = 4;\n\ntype PreviewPoint = { x: number; y: number };\ntype PreviewGesture = {\n  distance: number;\n  center: PreviewPoint;\n  zoom: number;\n  pan: PreviewPoint;\n};\n\nfunction clampPreviewZoom(value: number) {\n  return Math.min(MAX_PREVIEW_ZOOM, Math.max(MIN_PREVIEW_ZOOM, value));\n}\n\nfunction pointerDistance(a: PreviewPoint, b: PreviewPoint) {\n  return Math.hypot(b.x - a.x, b.y - a.y);\n}\n\nfunction pointerCenter(a: PreviewPoint, b: PreviewPoint): PreviewPoint {\n  return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 };\n}"
    ),
    (
        "  const [zoom, setZoom] = useState(1);\n  const hiddenRef = useRef(new Map<HTMLElement, string>());",
        "  const [zoom, setZoom] = useState(1);\n  const [pan, setPan] = useState<PreviewPoint>({ x: 0, y: 0 });\n  const hiddenRef = useRef(new Map<HTMLElement, string>());\n  const previewPointersRef = useRef(new Map<number, PreviewPoint>());\n  const previewGestureRef = useRef<PreviewGesture | null>(null);\n  const previewDragRef = useRef<{ point: PreviewPoint; pan: PreviewPoint } | null>(null);"
    ),
    (
        "  useEffect(() => {\n    if (token) return;\n    setRuntime(null); setHost(null); setFullscreen(false); setPreviewUrl(null); setOriginalUrl(null); setError(null); setMessage(null);\n  }, [token]);",
        "  useEffect(() => {\n    if (token) return;\n    setRuntime(null); setHost(null); setFullscreen(false); setPreviewUrl(null); setOriginalUrl(null); setError(null); setMessage(null);\n  }, [token]);\n\n  useEffect(() => {\n    if (fullscreen) return;\n    setZoom(1);\n    setPan({ x: 0, y: 0 });\n    previewPointersRef.current.clear();\n    previewGestureRef.current = null;\n    previewDragRef.current = null;\n  }, [fullscreen]);"
    ),
    (
        "  const refresh = useCallback(async () => { const data = await fetchRuntime(); if (data) setRuntime(data); }, [fetchRuntime]);",
        "  const refresh = useCallback(async () => { const data = await fetchRuntime(); if (data) setRuntime(data); }, [fetchRuntime]);\n\n  const updatePreviewZoom = useCallback((nextZoom: number) => {\n    const clamped = clampPreviewZoom(nextZoom);\n    setZoom(clamped);\n    if (clamped === 1) setPan({ x: 0, y: 0 });\n  }, []);\n\n  const handlePreviewPointerDown = useCallback((event: React.PointerEvent<HTMLDivElement>) => {\n    if (event.pointerType === 'mouse' && event.button !== 0) return;\n    event.currentTarget.setPointerCapture(event.pointerId);\n    const point = { x: event.clientX, y: event.clientY };\n    previewPointersRef.current.set(event.pointerId, point);\n    const points = Array.from(previewPointersRef.current.values());\n    if (points.length >= 2) {\n      const [first, second] = points;\n      previewGestureRef.current = {\n        distance: Math.max(1, pointerDistance(first, second)),\n        center: pointerCenter(first, second),\n        zoom,\n        pan,\n      };\n      previewDragRef.current = null;\n    } else if (zoom > 1) {\n      previewDragRef.current = { point, pan };\n    }\n  }, [pan, zoom]);\n\n  const handlePreviewPointerMove = useCallback((event: React.PointerEvent<HTMLDivElement>) => {\n    if (!previewPointersRef.current.has(event.pointerId)) return;\n    const point = { x: event.clientX, y: event.clientY };\n    previewPointersRef.current.set(event.pointerId, point);\n    const points = Array.from(previewPointersRef.current.values());\n    if (points.length >= 2 && previewGestureRef.current) {\n      event.preventDefault();\n      const [first, second] = points;\n      const gesture = previewGestureRef.current;\n      const center = pointerCenter(first, second);\n      const nextZoom = clampPreviewZoom(gesture.zoom * (pointerDistance(first, second) / gesture.distance));\n      setZoom(nextZoom);\n      setPan({\n        x: gesture.pan.x + center.x - gesture.center.x,\n        y: gesture.pan.y + center.y - gesture.center.y,\n      });\n      return;\n    }\n    if (points.length === 1 && zoom > 1 && previewDragRef.current) {\n      event.preventDefault();\n      const drag = previewDragRef.current;\n      setPan({ x: drag.pan.x + point.x - drag.point.x, y: drag.pan.y + point.y - drag.point.y });\n    }\n  }, [zoom]);\n\n  const handlePreviewPointerEnd = useCallback((event: React.PointerEvent<HTMLDivElement>) => {\n    previewPointersRef.current.delete(event.pointerId);\n    const points = Array.from(previewPointersRef.current.values());\n    if (points.length < 2) previewGestureRef.current = null;\n    if (points.length === 1 && zoom > 1) previewDragRef.current = { point: points[0], pan };\n    else if (points.length === 0) previewDragRef.current = null;\n    if (zoom <= 1) setPan({ x: 0, y: 0 });\n  }, [pan, zoom]);"
    ),
]

for old, new in replacements:
    count = source.count(old)
    if count != 1:
        raise SystemExit(f'expected one match, found {count}: {old[:100]!r}')
    source = source.replace(old, new, 1)

old_fullscreen = '''{fullscreen && documentUrl ? createPortal(<div className="fixed inset-0 z-[220] flex flex-col bg-black/95" dir="rtl"><div className="flex items-center justify-between px-4 pb-3 pt-[calc(12px+env(safe-area-inset-top))] text-white"><div><p className="text-sm font-bold">معاينة المستند</p><p className="text-[10px] text-white/60">{previewState === 'ready' ? 'نسخة WebP كاملة' : 'المستند الأصلي'}</p></div><button onClick={() => setFullscreen(false)} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10"><X className="h-5 w-5" /></button></div><div className="min-h-0 flex-1 overflow-auto px-3 py-2"><div className="flex min-h-full items-center justify-center">{previewState === 'ready' || !mime.includes('pdf') ? <img src={documentUrl} alt="المستند" className="max-w-none origin-center object-contain transition-transform" style={{ width: `${Math.max(100, zoom * 100)}%`, transform: `scale(${zoom})` }} /> : <iframe src={documentUrl} title="المستند الأصلي" className="h-full min-h-[80dvh] w-full bg-white" />}</div></div>{previewState === 'ready' || !mime.includes('pdf') ? <div className="flex items-center justify-center gap-3 border-t border-white/10 bg-black/80 px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3"><button onClick={() => setZoom((value) => Math.max(.75, value - .25))} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white"><ZoomOut className="h-5 w-5" /></button><span className="min-w-16 text-center text-xs font-bold text-white">{Math.round(zoom * 100)}%</span><button onClick={() => setZoom((value) => Math.min(3, value + .25))} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white"><ZoomIn className="h-5 w-5" /></button></div> : null}</div>, document.body) : null}'''

new_fullscreen = '''{fullscreen && documentUrl ? createPortal(<div className="fixed inset-0 z-[220] flex flex-col bg-black/95" dir="rtl"><div className="flex items-center justify-between px-4 pb-3 pt-[calc(12px+env(safe-area-inset-top))] text-white"><div><p className="text-sm font-bold">معاينة المستند</p><p className="text-[10px] text-white/60">{previewState === 'ready' ? 'قرّب بإصبعين واسحب الصورة' : 'المستند الأصلي'}</p></div><button onClick={() => setFullscreen(false)} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10"><X className="h-5 w-5" /></button></div><div className="min-h-0 flex-1 overflow-hidden px-3 py-2">{previewState === 'ready' || !mime.includes('pdf') ? <div className="flex h-full min-h-full touch-none select-none items-center justify-center overflow-hidden" style={{ touchAction: 'none' }} onPointerDown={handlePreviewPointerDown} onPointerMove={handlePreviewPointerMove} onPointerUp={handlePreviewPointerEnd} onPointerCancel={handlePreviewPointerEnd} onDoubleClick={() => updatePreviewZoom(zoom > 1 ? 1 : 2)}><img src={documentUrl} alt="المستند" draggable={false} className="max-h-full w-full max-w-full origin-center object-contain will-change-transform" style={{ transform: `translate3d(${pan.x}px, ${pan.y}px, 0) scale(${zoom})`, transition: previewPointersRef.current.size ? 'none' : 'transform 120ms ease-out' }} /></div> : <iframe src={documentUrl} title="المستند الأصلي" className="h-full min-h-[80dvh] w-full bg-white" />}</div>{previewState === 'ready' || !mime.includes('pdf') ? <div className="flex items-center justify-center gap-3 border-t border-white/10 bg-black/80 px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3"><button onClick={() => updatePreviewZoom(zoom - .25)} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white" aria-label="تصغير"><ZoomOut className="h-5 w-5" /></button><button onClick={() => updatePreviewZoom(1)} className="min-w-16 rounded-full px-3 py-2 text-center text-xs font-bold text-white" aria-label="إعادة الضبط">{Math.round(zoom * 100)}%</button><button onClick={() => updatePreviewZoom(zoom + .25)} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white" aria-label="تكبير"><ZoomIn className="h-5 w-5" /></button></div> : null}</div>, document.body) : null}'''

if source.count(old_fullscreen) != 1:
    raise SystemExit(f'fullscreen replacement expected one match, found {source.count(old_fullscreen)}')
source = source.replace(old_fullscreen, new_fullscreen, 1)
path.write_text(source, encoding='utf-8')
print('Pinch zoom and pan support added.')
