import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type J = Record<string, unknown>;
type MediaAsset = { id:string; asset_key:string; title:string; asset_type:"image"|"document"; public_url:string; filename?:string; mime_type?:string; caption_template?:string; version?:number; health_status?:string; };

const SB=Deno.env.get("SUPABASE_URL")!;
const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const IK=Deno.env.get("SANAD_INTERNAL_API_KEY")!;
const WA=Deno.env.get("META_WA_ACCESS_TOKEN")!;
const PID=Deno.env.get("META_WA_PHONE_NUMBER_ID")!;
const GEM=Deno.env.get("GEMINI_API_KEY")!;
const VER="sanad-assistant-v16-support-fallback";
const GRAPH=`https://graph.facebook.com/${Deno.env.get("META_GRAPH_VERSION")||"v20.0"}`;
const APP="https://app.sanadflow.com";
const INSTALL=`${APP}/install/`;

function clean(v:unknown,max=12000){const s=String(v??"").replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).trim();return s.length>max?`${s.slice(0,max-1)}…`:s}
function norm(v:unknown){return clean(v).toLowerCase().replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[ًٌٍَُِّْـ]/g,"").replace(/\s+/g," ").trim()}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function sbHeaders(extra:J={}){return{apikey:KEY,Authorization:`Bearer ${KEY}`,...extra}}
async function rpc(name:string,body:J){const r=await fetch(`${SB}/rest/v1/rpc/${name}`,{method:"POST",headers:sbHeaders({"content-type":"application/json"}),body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw new Error(`rpc_${name}_${r.status}:${t.slice(0,700)}`);return t?JSON.parse(t):null}
async function meta(path:string,init:RequestInit={}){const r=await fetch(`${GRAPH}${path}`,{...init,headers:{Authorization:`Bearer ${WA}`,...(init.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(`meta_${r.status}:${t.slice(0,900)}`);return t?JSON.parse(t):null}
async function sendText(to:string,body:string){const x=await meta(`/${PID}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",recipient_type:"individual",to,type:"text",text:{preview_url:true,body}})});return x?.messages?.[0]?.id||null}

async function runTool<T>(c:any,name:string,input:J,fn:()=>Promise<T>):Promise<T>{const started=Date.now();let id:number|null=null;try{id=await rpc("start_sanad_assistant_tool_execution",{p_assistant_message_id:c.id,p_conversation_id:c.conversation_id,p_tool_name:name,p_input:input});const out=await fn();await rpc("finish_sanad_assistant_tool_execution",{p_execution_id:id,p_status:"completed",p_output:JSON.parse(JSON.stringify(out??{})),p_error_code:null,p_error_message:null,p_latency_ms:Date.now()-started});return out}catch(e){if(id)await rpc("finish_sanad_assistant_tool_execution",{p_execution_id:id,p_status:"failed",p_output:{},p_error_code:clean(e instanceof Error?e.message:e,120).split(":")[0],p_error_message:clean(e instanceof Error?e.message:e,900),p_latency_ms:Date.now()-started}).catch(()=>{});throw e}}
async function allowed(ctx:any,tool:string){return Boolean(await rpc("is_sanad_assistant_tool_allowed",{p_audience:ctx?.audience||"new_user",p_tool_name:tool}))}
async function transition(c:any,args:{stage:string;flow?:string|null;expected?:string|null;action?:string|null;reason?:string|null;ttl?:number;meta?:J}){return runTool(c,"transition_sanad_assistant_conversation",args,()=>rpc("transition_sanad_assistant_conversation",{p_conversation_id:c.conversation_id,p_next_stage:args.stage,p_next_flow:args.flow??null,p_expected_input_type:args.expected??null,p_completed_action:args.action??null,p_exit_reason:args.reason??null,p_ttl_minutes:args.ttl??30,p_state_metadata:args.meta??{}}))}
function safeName(ctx:any){const s=clean(ctx?.contact?.safe_display_name||ctx?.user?.full_name,80).replace(/[\"'`«»『』【】✨🌟💫⭐️]+/g," ").replace(/\s+/g," ").trim();if(!s||s.length<2||s.length>40)return"";return s.split(" ")[0]}
function businessName(ctx:any){return clean(ctx?.businesses?.owned?.[0]?.name||ctx?.businesses?.memberships?.[0]?.name,120)}
function referenceFrom(text:string){return text.match(/[0-9a-f]{8}-[0-9a-f-]{27,}/i)?.[0]||text.match(/\b\d{6,20}\b/)?.[0]||null}

function deterministic(text:string,ctx:any){const n=norm(text),flow=ctx?.conversation?.active_flow;
 if(flow==="new_user_menu"&&/^[123]$/.test(n))return n==="1"?"submit_payment_notice":n==="2"?"install_app":"create_business";
 if(/^(مرحبا|اهلا|السلام عليكم|هلا|صباح الخير|مساء الخير)[.!، ]*$/.test(n))return"greeting";
 if(/^(شكرا|شكرًا|مشكور|يعطيك العافيه|جزاك الله خير)[.!، ]*$/.test(n))return"thanks";
 if(/^(مع السلامه|في امان الله|الى اللقاء|باي)[.!، ]*$/.test(n))return"goodbye";
 if(/^(تمام|حسنا|طيب|اوكي|موافق|نعم|ايوه)[.!، ]*$/.test(n))return"acknowledgement";
 if(/(هل تعرف من انا|من انا|ماذا تعرف عني)/.test(n))return"identity";
 if(/(كم|عدد).*(مستخدم|مسجل|تسجيل|عمليه|رساله|تذكره)/.test(n)&&ctx?.capabilities?.is_platform_admin)return"platform_metric";
 if(/(ملف|مواد|صفحه|طباعه|اطبع|ملصق|ستيكر|استيكر|بطاقه الكاشير|qr|كيو ار).*(طباع|ملصق|qr|كيو ار|كاشير|سند)|(ارسل|اعطني|ابغى|اريد|هات).*(ملف|مواد|ملصق|ستيكر|استيكر|بطاقه)/.test(n))return"download_sticker";
 if(/(اريد|ابغى|كيف|حاب).*(ارسال|ارسل|رفع).*(اشعار)|(ارسال|رفع).*(اشعار)/.test(n))return"submit_payment_notice";
 if(/(حاله|وين|اين|تابع|متابعه).*(عمليه|اشعار)|(تحقق).*(عمليه)/.test(n))return"check_operation";
 if(/(موظف|كاشير|فريق).*(اضف|اضافه|اداره|صلاح)/.test(n))return"add_employee";
 if(/(انشئ|انشاء|افتح|شغل|تشغيل).*(نشاط|متجر|محل|سند)/.test(n))return"create_business";
 if(/(مشكله|لا يعمل|خطا|دعم|موظف بشري|شكوى|اشتكي|تصعيد|حذف الحساب|احذف حساب|الغاء الحساب|الغي الحساب|مدير سند)/.test(n))return"human_support";
 if(/(ثبت|تثبيت|تنزيل|تحميل|رابط|نسخه).*(سند|التطبيق)|(سند|التطبيق).*(ثبت|تثبيت|تنزيل|تحميل|رابط|نسخه)/.test(n))return"install_app";
 if(/(اشتراك|سند برو|باقه|pro)/.test(n))return"subscription_question";
 if(/(ما هو سند|ماهو سند|كيف يعمل سند|ماذا يحل|عرفني بسند)/.test(n))return"knowledge_inquiry";
 return"unknown"}

async function semanticIntent(text:string,ctx:any){const prompt=`صنف الرسالة إلى نية واحدة فقط من هذه القائمة: greeting,thanks,goodbye,acknowledgement,identity,install_app,submit_payment_notice,check_operation,create_business,add_employee,download_sticker,subscription_question,human_support,platform_metric,knowledge_inquiry,unknown. أعد JSON فقط بالشكل {"intent":"...","confidence":0.0}. الرسالة: ${text}. الجمهور: ${ctx?.audience||"new_user"}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(GEM)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0,responseMimeType:"application/json"}})});const z=await r.json();if(!r.ok)throw new Error(`intent_gemini_${r.status}`);try{return JSON.parse(clean(z?.candidates?.[0]?.content?.parts?.[0]?.text,500))}catch{return{intent:"unknown",confidence:0}}}
async function classify(c:any,text:string,ctx:any){const d=deterministic(text,ctx);if(d!=="unknown")return{intent:d,confidence:.99,source:"rules"};const alias=await runTool(c,"lookup_sanad_assistant_intent_alias",{text},()=>rpc("lookup_sanad_assistant_intent_alias",{p_text:text})).catch(()=>null);if(alias?.intent)return{intent:alias.intent,confidence:.97,source:"alias"};const sem=await runTool(c,"semantic_intent_classifier",{text},()=>semanticIntent(text,ctx)).catch(()=>({intent:"unknown",confidence:0}));return{intent:sem.intent||"unknown",confidence:Number(sem.confidence||0),source:"semantic"}}

function requestedPrintKeys(text:string){const n=norm(text),qr=/(qr|كيو ار)/.test(n),phone=/(رقم|جوال|هاتف|783)/.test(n),single=/(بطاقه الكاشير|كاشير|نسخه واحده|تنسيق واحد)/.test(n);if(qr&&!phone&&!single)return["sanad-qr-sticker-a4"];if(phone&&!qr&&!single)return["sanad-phone-sticker-a4"];if(single&&!qr&&!phone)return["sanad-counter-card"];return["sanad-qr-sticker-a4","sanad-phone-sticker-a4","sanad-counter-card"]}

async function selectMedia(c:any,p:{intent:string;audience?:string;stage?:string;keys?:string[];limit?:number;force?:boolean}){return runTool(c,"select_sanad_assistant_media",p,()=>rpc("select_sanad_assistant_media",{p_conversation_id:c.conversation_id,p_intent:p.intent,p_audience:p.audience||null,p_journey_stage:p.stage||null,p_requested_keys:p.keys||null,p_limit:p.limit||1,p_force:Boolean(p.force)}))}
async function registerMedia(c:any,a:MediaAsset,status:string,externalId:string|null,error?:string){await rpc("register_sanad_assistant_media_delivery",{p_conversation_id:c.conversation_id,p_assistant_message_id:c.id,p_asset_id:a.id,p_intent:c._intent,p_reason:c._mediaReason||"contextual",p_send_status:status,p_external_message_id:externalId,p_error_code:error?error.split(":")[0]:null,p_error_message:error||null,p_latency_ms:null,p_metadata:{asset_key:a.asset_key,asset_version:a.version||1}})}
async function sendMedia(c:any,phone:string,a:MediaAsset,caption?:string){const started=Date.now();try{const head=await fetch(a.public_url,{method:"HEAD",redirect:"follow"});if(!head.ok){await rpc("mark_sanad_assistant_media_health",{p_asset_id:a.id,p_health_status:"unhealthy",p_http_status:head.status,p_error:`http_${head.status}`}).catch(()=>{});throw new Error(`asset_unreachable_${head.status}`)}await rpc("mark_sanad_assistant_media_health",{p_asset_id:a.id,p_health_status:"healthy",p_http_status:head.status,p_error:null}).catch(()=>{});const payload=a.asset_type==="document"?{messaging_product:"whatsapp",recipient_type:"individual",to:phone,type:"document",document:{link:a.public_url,filename:a.filename||`${a.asset_key}.pdf`,caption:clean(caption||a.caption_template||a.title,1000)}}:{messaging_product:"whatsapp",recipient_type:"individual",to:phone,type:"image",image:{link:a.public_url,caption:clean(caption||a.caption_template||a.title,1000)}};const x=await meta(`/${PID}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const id=x?.messages?.[0]?.id||null;await registerMedia(c,a,id?"accepted":"failed",id);return{ok:Boolean(id),externalId:id,assetKey:a.asset_key,latencyMs:Date.now()-started}}catch(e){const m=clean(e instanceof Error?e.message:e,700);await registerMedia(c,a,"failed",null,m).catch(()=>{});return{ok:false,assetKey:a.asset_key,error:m,latencyMs:Date.now()-started}}}

async function structuredAnswer(c:any,question:string,intent:string,ctx:any){const knowledge=await runTool(c,"search_sanad_knowledge",{question,intent},()=>rpc("search_sanad_knowledge",{p_query:question,p_intent:intent,p_scope:null,p_audience:ctx?.audience||null,p_channel:"whatsapp",p_reference_url:null,p_source_code:null,p_limit:6}));const prompt=`أنت مساعد سند الرسمي. أعد JSON فقط: {"answer":"نص عربي مختصر وعملي","needs_clarification":false,"clarification":"","confidence":0.0}. لا تخترع روابط أو أسعار أو حالات. لا تدّع تنفيذ إجراء. سند ينظم ما بعد الدفع ولا يؤكد التسوية البنكية. السؤال:${question}\nالسياق:${JSON.stringify({audience:ctx?.audience,user:ctx?.user,businesses:ctx?.businesses,subscription:ctx?.subscription,operations:ctx?.operations}).slice(0,6500)}\nالمعرفة:${JSON.stringify(knowledge?.items||[]).slice(0,14000)}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(GEM)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.12,responseMimeType:"application/json"}})});const z=await r.json();if(!r.ok)throw new Error(`gemini_${r.status}`);return JSON.parse(clean(z?.candidates?.[0]?.content?.parts?.[0]?.text,4200))}
function qualityGate(answer:string){let a=clean(answer,3800);if(!a)a="وضّح لي ما الذي تريد إنجازه في سند، وسأرشدك إلى الخطوة المناسبة.";a=a.replace(/https?:\/\/[^\s]+/g,u=>(u.startsWith(APP)||u.includes("supabase.co")?u:""));if(a.length>3800)a=a.slice(0,3790)+"…";return a}
async function complete(c:any,answer:string,externalId:string|null,intent:string,confidence:number,started:number,metadata:J,tools:any[]){await rpc("complete_sanad_assistant_message",{p_message_id:c.id,p_response_text:answer,p_external_response_id:externalId,p_transcript:null,p_intent:intent,p_confidence:confidence,p_tool_calls:tools,p_model:c.settings?.model||"gemini-2.5-flash",p_prompt_version:VER,p_input_tokens:0,p_output_tokens:0,p_latency_ms:Date.now()-started,p_metadata:{assistant_version:VER,text_first:true,...metadata}})}

async function processMessage(messageId:string){const started=Date.now();const c=await rpc("claim_sanad_assistant_message",{p_message_id:messageId});if(!c?.id)return{processed:false};const phone=String(c.contact?.phone||"");const text=clean(c.body_text||c.transcript);const ctx=await runTool(c,"get_sanad_assistant_user_context",{},()=>rpc("get_sanad_assistant_user_context",{p_conversation_id:c.conversation_id}));const support=await rpc("get_sanad_public_support",{}).catch(()=>({}));const supportPhone=clean(support?.support_whatsapp,40);const supportLine=supportPhone?`\n\nللتواصل مباشرة مع *مدير سند* عبر واتساب:\n*${supportPhone}*`:"";const cls=await classify(c,text,ctx);const intent=cls.intent;c._intent=intent;const audience=ctx?.audience||(ctx?.user?.is_registered?"registered":"new_user");const tools:any[]=[{tool:"get_sanad_assistant_user_context",status:"success"},{tool:"intent_classifier",status:"success",source:cls.source}];let answer="",externalId:string|null=null,media:any[]=[];const name=safeName(ctx),biz=businessName(ctx);

 if(intent==="thanks")answer=name?`العفو يا ${name} 🌿`:"على الرحب والسعة 🌿";
 else if(intent==="goodbye")answer="في أمان الله، ونحن هنا متى احتجت إلى سند.";
 else if(intent==="acknowledgement")answer="تمام ✅";
 else if(intent==="greeting"){if(ctx?.user?.is_registered)answer=biz?`أهلًا ${name||"بك"} 👋\n\nأنا معك في تشغيل سند داخل *${biz}*، ومراجعة العمليات والفريق ومواد الطباعة.\n\nما الذي تريد إنجازه الآن؟`:`أهلًا ${name||"بك"} 👋\n\nاكتب ما تريد إنجازه في سند مباشرة.`;else{answer="أهلًا بك في سند 👋\n\nسند ينظم ما يحدث بعد الدفع الإلكتروني.\n\nاكتب رقم الخيار:\n1 — إرسال إشعار دفع\n2 — تثبيت تطبيق سند\n3 — تشغيل سند في متجري";await transition(c,{stage:"discovery",flow:"new_user_menu",expected:"text_choice",action:"new_user_intro_sent",ttl:30})}}
 else if(intent==="identity")answer=ctx?.user?.is_registered?`هذا الرقم مرتبط بحساب *${clean(ctx.user.full_name,180)}* ✅${biz?`\nالنشاط: *${biz}*.`:""}${ctx?.subscription?.is_current?`\nالاشتراك: *${clean(ctx.subscription.plan_name||ctx.subscription.plan_code,100)}*.`:""}`:"هذا الرقم غير مرتبط بحساب سند حتى الآن، ويمكنك إرسال إشعار دفع هنا دون تثبيت التطبيق.";
 else if(intent==="submit_payment_notice"){answer=`${name?`أهلًا ${name}، `:""}أرسل إشعار الدفع هنا كـ *صورة أو ملف PDF* 📎\n\nسند سيحفظه ويحلله ثم يرسل لك رابط التحقق ورمز QR. لا تحتاج إلى تثبيت التطبيق.`;await transition(c,{stage:"payment_notice_submission",flow:"submit_payment_notice",expected:"image_or_pdf",action:"payment_notice_instructions_sent",ttl:45});if(await allowed(ctx,"select_sanad_assistant_media")){c._mediaReason="explain_submission_flow";const assets=await selectMedia(c,{intent,audience,stage:"payment_notice_submission",limit:1});for(const a of assets||[])media.push(await sendMedia(c,phone,a))}}
 else if(intent==="install_app"){answer=`📱 *تثبيت تطبيق سند*\n\n${INSTALL}\n\n• Android: افتح الرابط ثم اختر *تثبيت التطبيق*.\n• iPhone: افتحه في Safari، ثم *مشاركة* ← *إضافة إلى الشاشة الرئيسية*.\n\nإذا فتح الرابط داخل Facebook، افتحه في Chrome أو Safari.`;await transition(c,{stage:"activation",flow:null,action:"install_link_sent",reason:"topic_completed",ttl:0});if(await allowed(ctx,"select_sanad_assistant_media")){c._mediaReason="installation_guidance";const assets=await selectMedia(c,{intent,audience,stage:"activation",limit:1});for(const a of assets||[])media.push(await sendMedia(c,phone,a))}}
 else if(intent==="create_business"){answer=`*تشغيل سند في نشاطك*\n\n1. أنشئ ملف النشاط.\n2. أكمل الاسم والشعار والتواصل.\n3. أضف الفريق والكاشير.\n4. حمّل مواد الطباعة.\n5. نفّذ أول عملية تجريبية.\n\nابدأ من:\n${APP}`;await transition(c,{stage:"business_activation",flow:null,action:"business_activation_steps_sent",reason:"topic_completed",ttl:0})}
 else if(intent==="download_sticker"){if(!await allowed(ctx,"select_sanad_assistant_media"))answer="مواد الطباعة متاحة لمالك النشاط أو مديره المخوّل.";else{const keys=requestedPrintKeys(text);answer=keys.length===1?"سأرسل لك الآن ملف الطباعة المعتمد مباشرة.":"سأرسل لك الآن حزمة الطباعة المعتمدة.";c._mediaReason="explicit_print_request";const assets=await selectMedia(c,{intent,audience:"business_owner",stage:"business_activation",keys,limit:keys.length,force:true});for(const a of assets||[])media.push(await sendMedia(c,phone,a,a.caption_template));if(!(assets||[]).length)answer="لم أجد ملف الطباعة المعتمد حاليًا. تم منع إرسال أي رابط غير موثوق."}}
 else if(intent==="check_operation"){if(!await allowed(ctx,"assistant_get_operation_status"))answer="لا أستطيع عرض عمليات هذا الحساب.";else{const op=await runTool(c,"assistant_get_operation_status",{reference:referenceFrom(text)},()=>rpc("assistant_get_operation_status",{p_conversation_id:c.conversation_id,p_reference:referenceFrom(text)}));answer=!op?.found?"لم أجد عملية مرتبطة بهذا الرقم أو المرجع. أرسل رابط العملية أو رقم المرجع.":`*حالة العملية*\n\n• الحالة: *${clean(op.operation.status,80)}*\n• التحليل: *${clean(op.operation.ai_status,80)}*${op.operation.amount?`\n• المبلغ: *${op.operation.amount} ${op.operation.currency||""}*`:""}${op.operation.financial_entity?`\n• الجهة: ${clean(op.operation.financial_entity,120)}`:""}\n\nرابط المراجعة:\n${op.operation.verification_url}`}}
 else if(intent==="platform_metric"){if(!await allowed(ctx,"assistant_get_platform_metrics"))answer="هذه الإحصائية متاحة فقط لمدير المنصة.";else{const n=norm(text);const metric=/(عمليه)/.test(n)?"new_operations":/(رساله)/.test(n)?"assistant_inbound_messages":/(تذكره)/.test(n)?"open_support_tickets":"new_users";const days=Number(n.match(/(\d+)\s*(يوم|ايام)/)?.[1]||2);const r=await runTool(c,"assistant_get_platform_metrics",{metric,days},()=>rpc("assistant_get_platform_metrics",{p_conversation_id:c.conversation_id,p_metric:metric,p_date_from:new Date(Date.now()-days*86400000).toISOString(),p_date_to:new Date().toISOString()}));answer=r?.ok?`خلال آخر *${days} يوم*، بلغ ${metric==="new_users"?"عدد المستخدمين الجدد":metric==="new_operations"?"عدد العمليات الجديدة":metric==="assistant_inbound_messages"?"عدد الرسائل الواردة":"عدد تذاكر الدعم المفتوحة"}: *${r.value}*.`:"تعذر جلب الإحصائية المطلوبة."}}
 else if(intent==="human_support"){if(!await allowed(ctx,"assistant_create_support_ticket"))answer=`تعذر إنشاء طلب دعم تلقائيًا.${supportLine}`;else{const t=await runTool(c,"assistant_create_support_ticket",{category:norm(text).includes("شكوى")?"complaint":"support"},()=>rpc("assistant_create_support_ticket",{p_conversation_id:c.conversation_id,p_message_id:c.id,p_category:norm(text).includes("شكوى")?"complaint":"support",p_subject:"طلب دعم عبر مساعد سند",p_description:text,p_priority:norm(text).includes("عاجل")?"urgent":"normal",p_metadata:{assistant_version:VER}}));answer=`تم تسجيل طلبك لدى دعم سند ✅\n\nرقم المتابعة: *${t?.ticket_id}*${supportLine}\n\nلا ترسل كلمة مرور أو رمز تحقق.`}}
 else if(intent==="knowledge_inquiry")answer="سند ليس أداة دفع، بل طبقة تنظيم لما بعد الدفع الإلكتروني. يرسل العميل إشعار الدفع، فيتحول إلى عملية منظمة تحتوي على رابط وQR يمكن للكاشير مراجعتها وتوثيق التحقق منها دون أخذ هاتف العميل.";
 else if(intent==="unknown" || cls.confidence<0.60){let ticket:any=null;if(await allowed(ctx,"assistant_create_support_ticket")){ticket=await runTool(c,"assistant_create_support_ticket",{category:"unrecognized_request"},()=>rpc("assistant_create_support_ticket",{p_conversation_id:c.conversation_id,p_message_id:c.id,p_category:"support",p_subject:"طلب لم يفهمه مساعد سند",p_description:text,p_priority:"normal",p_metadata:{assistant_version:VER,intent_source:cls.source,confidence:cls.confidence}})).catch(()=>null)}answer=`لم أفهم طلبك بشكل كافٍ، لذلك أحلتك إلى *مدير سند* بدل أن أخمّن إجابة.${ticket?.ticket_id?`\n\nرقم المتابعة: *${ticket.ticket_id}*`:""}${supportLine}\n\nلا ترسل كلمة مرور أو رمز تحقق.`;}
 else{try{const x=await runTool(c,"structured_generation",{text,intent},()=>structuredAnswer(c,text,intent,ctx));answer=x?.needs_clarification?(x.clarification||"وضّح لي طلبك أكثر."):(x.answer||"");}catch{answer=`لم أفهم الطلب بدقة.${supportLine}`}}

 answer=qualityGate(answer);externalId=await sendText(phone,answer);if(["thanks","goodbye","acknowledgement","identity","platform_metric","check_operation","human_support","unknown"].includes(intent))await transition(c,{stage:ctx?.conversation?.journey_stage||"active",flow:null,action:`${intent}_completed`,reason:"topic_completed",ttl:0}).catch(()=>{});const failed=media.filter((x:any)=>!x.ok);await complete(c,answer,externalId,intent,cls.confidence,started,{intent_source:cls.source,audience,media_attempts:media,media_sent:media.length-failed.length,media_failed:failed.length,support_source:"app_public_information"},tools);return{processed:true,intent,intent_source:cls.source,media_sent:media.length-failed.length,media_failed:failed.length,assistant_version:VER}}

Deno.serve(async req=>{if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);if(req.headers.get("x-sanad-internal-key")!==IK)return json({ok:false,error:"unauthorized"},401);let b:any;try{b=await req.json()}catch{return json({ok:false,error:"invalid_json"},400)}const id=String(b?.message_id||"");if(!/^[0-9a-f-]{36}$/i.test(id))return json({ok:false,error:"invalid_message_id"},400);try{return json({ok:true,...await processMessage(id)})}catch(e){console.error(JSON.stringify({event:"assistant_processing_failed",error:clean(e instanceof Error?e.message:e,1200)}));return json({ok:false,error:"assistant_processing_failed",assistant_version:VER},500)}});
