import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type J = Record<string, unknown>;
const SB=Deno.env.get("SUPABASE_URL")!, KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, IK=Deno.env.get("SANAD_INTERNAL_API_KEY")!;
const ENGINE_URL=`${SB}/functions/v1/sanad-v3-assistant-engine`;
const CANDIDATE="sanad-assistant-v15-contextual-engine-candidate";
const ENGINE="sanad-conversation-engine-v3-contextual";
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function headers(extra:J={}){return{apikey:KEY,Authorization:`Bearer ${KEY}`,...extra}}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${SB}/rest/v1/${path}`,{...init,headers:headers(init.headers as J||{})});const tx=await r.text();if(!r.ok)throw new Error(`rest_${r.status}:${tx.slice(0,1000)}`);return tx?JSON.parse(tx):null}
async function rpc(name:string,body:J){return await rest(`rpc/${name}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)})}
function mediaKeys(metadata:any):string[]{const a=Array.isArray(metadata?.media_attempts)?metadata.media_attempts:[];return a.map((x:any)=>String(x?.assetKey||"")).filter(Boolean).sort()}
function sameMembers(a:string[]=[],b:string[]=[]){return a.length===b.length&&a.every(x=>b.includes(x))}
function similarity(a:string,b:string){const tok=(s:string)=>new Set(String(s||"").toLowerCase().replace(/[^\p{L}\p{N}\s]/gu," ").split(/\s+/).filter(x=>x.length>1));const x=tok(a),y=tok(b),u=new Set([...x,...y]);if(!u.size)return 1;let i=0;for(const z of x)if(y.has(z))i++;return Number((i/u.size).toFixed(3))}
function family(v:string|null){const x=String(v||"");if(["faq","knowledge_inquiry","subscription_question","digital_content","external_link_context"].includes(x))return"knowledge";if(["memory","identity"].includes(x))return"memory";if(["support","human_support","check_operation","get_original_notice"].includes(x))return"support";if(["install_app","submit_payment_notice","create_business","download_sticker","add_employee"].includes(x))return"action";return x}
async function enginePlan(text:string,audience:string,context:any){const r=await fetch(ENGINE_URL,{method:"POST",headers:{"content-type":"application/json","x-sanad-internal-key":IK},body:JSON.stringify({text,audience,context})});const b=await r.json();if(!r.ok||!b?.ok||!b?.plan)throw new Error(`engine_${r.status}:${JSON.stringify(b).slice(0,400)}`);return b.plan}
async function compareMessage(messageId:string){
 const inbound=(await rest(`sanad_assistant_messages?id=eq.${messageId}&direction=eq.inbound&select=id,conversation_id,body_text,transcript,intent,prompt_version,metadata,created_at`))?.[0];if(!inbound)throw new Error("inbound_message_not_found");
 const outbound=(await rest(`sanad_assistant_messages?conversation_id=eq.${inbound.conversation_id}&direction=eq.outbound&created_at=gt.${encodeURIComponent(inbound.created_at)}&order=created_at.asc&limit=1&select=id,body_text,intent,prompt_version,metadata,created_at`))?.[0]||null;
 const context=await rpc("get_sanad_assistant_context_snapshot",{p_conversation_id:inbound.conversation_id,p_before_message_id:inbound.id});
 const audience=String(inbound.metadata?.audience||context?.conversation_metadata?.audience||"guest");
 const t0=Date.now(),plan=await enginePlan(String(inbound.body_text||inbound.transcript||""),audience,context),latency=Date.now()-t0;
 const productionMedia=mediaKeys(outbound?.metadata||inbound.metadata),candidateMedia=Array.isArray(plan.media_keys)?plan.media_keys.map(String).sort():[];
 const pIntent=outbound?.intent||inbound.intent||null,cIntent=plan.intent||null;
 const row={inbound_message_id:inbound.id,conversation_id:inbound.conversation_id,production_assistant_version:outbound?.prompt_version||inbound.prompt_version||null,production_intent:pIntent,production_intent_family:family(pIntent),production_response:outbound?.body_text||null,production_media_keys:productionMedia,candidate_assistant_version:CANDIDATE,candidate_engine_version:plan.engine_version||ENGINE,candidate_intent:cIntent,candidate_intent_family:plan.intent_family||family(cIntent),candidate_response:plan.response||null,candidate_media_keys:candidateMedia,intent_match:Boolean(pIntent&&pIntent===cIntent),semantic_intent_match:family(pIntent)===(plan.intent_family||family(cIntent)),media_match:sameMembers(productionMedia,candidateMedia),response_similarity:similarity(outbound?.body_text||"",plan.response||""),safety_flags:Array.isArray(plan.safety_flags)?plan.safety_flags:[],candidate_latency_ms:latency,comparison_status:"completed",metadata:{audience,active_flow:context?.active_flow||null,journey_stage:context?.journey_stage||null,recent_messages:Array.isArray(context?.recent_messages)?context.recent_messages.length:0,recent_media:Array.isArray(context?.recent_media)?context.recent_media.length:0,production_outbound_message_id:outbound?.id||null,compared_at:new Date().toISOString(),entities:plan.entities||{},context_used:plan.context_used||{}}};
 await rest("sanad_assistant_shadow_comparisons?on_conflict=inbound_message_id,candidate_assistant_version",{method:"POST",headers:{"content-type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row)});return row;
}
Deno.serve(async req=>{if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);if(req.headers.get("x-sanad-internal-key")!==IK)return json({ok:false,error:"unauthorized"},401);let b:any;try{b=await req.json()}catch{return json({ok:false,error:"invalid_json"},400)}const ids=Array.isArray(b?.message_ids)?b.message_ids.map(String):b?.message_id?[String(b.message_id)]:[];if(!ids.length)return json({ok:false,error:"message_id_required"},400);const results=[];for(const id of ids.slice(0,100)){try{results.push({ok:true,message_id:id,comparison:await compareMessage(id)})}catch(e){results.push({ok:false,message_id:id,error:String(e)})}}return json({ok:true,candidate_version:CANDIDATE,engine_version:ENGINE,processed:results.length,succeeded:results.filter((x:any)=>x.ok).length,failed:results.filter((x:any)=>!x.ok).length,results})});
