name: sanad_local
description: SANAD Local cashier-first Android application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: 2.4.2+1
  path_provider: ^2.1.6
  path: ^1.9.1
  uuid: ^4.6.0
  image_picker: ^1.2.3
  crypto: ^3.0.6
  http: ^1.6.0
  intl: ^0.20.2
  pdf: ^3.13.0
  printing: ^5.15.0
  flutter_tesseract_ocr: ^0.4.31
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata_config.json
    - assets/tessdata/
    - assets/fonts/
    - assets/test/
