-- Read-only catalog exporter for the SANAD-owned schema surface.
--
-- Scope:
--   * public, private, and app schemas
--   * policies attached to storage tables (the tables remain Supabase-managed)
--
-- Deliberately excluded:
--   * table rows, auth users, storage objects, Vault secrets, and cron commands
--   * Supabase-managed auth/storage/realtime/net/cron table definitions
--
-- Output is base64-encoded UTF-8 chunks so the extraction transport cannot alter
-- function bodies. The generated SQL still requires review and isolated replay.

with recursive
scope as (
  select array['app', 'private', 'public']::text[] as owned_schemas
),
sequence_ddl as (
  select
    20 as section_order,
    format('%I.%I', n.nspname, c.relname) as object_key,
    format(
      E'create sequence %I.%I as %s increment by %s minvalue %s maxvalue %s start with %s cache %s %s;\n',
      n.nspname,
      c.relname,
      format_type(s.seqtypid, null),
      s.seqincrement,
      s.seqmin,
      s.seqmax,
      s.seqstart,
      s.seqcache,
      case when s.seqcycle then 'cycle' else 'no cycle' end
    ) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_sequence s on s.seqrelid = c.oid
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and c.relkind = 'S'
    and not exists (
      select 1
      from pg_depend identity_dependency
      where identity_dependency.classid = 'pg_class'::regclass
        and identity_dependency.objid = c.oid
        and identity_dependency.deptype = 'i'
    )
),
column_ddl as (
  select
    n.nspname,
    c.relname,
    a.attnum,
    format(
      '  %I %s%s%s%s%s',
      a.attname,
      format_type(a.atttypid, a.atttypmod),
      case
        when a.attcollation <> 0 and a.attcollation <> t.typcollation
          then format(' collate %I.%I', cn.nspname, coll.collname)
        else ''
      end,
      case a.attidentity
        when 'a' then ' generated always as identity'
        when 'd' then ' generated by default as identity'
        else ''
      end,
      case
        when a.attgenerated = 's'
          then format(' generated always as (%s) stored', pg_get_expr(ad.adbin, ad.adrelid))
        when a.attidentity = '' and ad.oid is not null
          then format(' default %s', pg_get_expr(ad.adbin, ad.adrelid))
        else ''
      end,
      case when a.attnotnull then ' not null' else '' end
    ) as ddl
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  join pg_type t on t.oid = a.atttypid
  left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
  left join pg_collation coll on coll.oid = a.attcollation
  left join pg_namespace cn on cn.oid = coll.collnamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and c.relkind in ('r', 'p')
    and a.attnum > 0
    and not a.attisdropped
),
pre_table_function_oids(oid) as (
  select distinct dep.refobjid
  from pg_attrdef ad
  join pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum
  join pg_class c on c.oid = ad.adrelid
  join pg_namespace n on n.oid = c.relnamespace
  join pg_depend dep
    on dep.classid = 'pg_attrdef'::regclass
   and dep.objid = ad.oid
   and dep.refclassid = 'pg_proc'::regclass
  join pg_proc referenced_proc on referenced_proc.oid = dep.refobjid
  join pg_namespace referenced_namespace on referenced_namespace.oid = referenced_proc.pronamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and referenced_namespace.nspname = any(scope.owned_schemas)

  union

  select distinct dep.refobjid
  from pre_table_function_oids current_proc
  join pg_depend dep
    on dep.classid = 'pg_proc'::regclass
   and dep.objid = current_proc.oid
   and dep.refclassid = 'pg_proc'::regclass
  join pg_proc referenced_proc on referenced_proc.oid = dep.refobjid
  join pg_namespace referenced_namespace on referenced_namespace.oid = referenced_proc.pronamespace
  cross join scope
  where referenced_namespace.nspname = any(scope.owned_schemas)
),
pre_table_function_ddl as (
  select
    25 as section_order,
    format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) as object_key,
    pg_get_functiondef(p.oid) || E';\n' as ddl
  from pre_table_function_oids required
  join pg_proc p on p.oid = required.oid
  join pg_namespace n on n.oid = p.pronamespace
),
table_ddl as (
  select
    30 as section_order,
    format('%I.%I', nspname, relname) as object_key,
    format(
      E'create table %I.%I (\n%s\n);\n',
      nspname,
      relname,
      string_agg(ddl, E',\n' order by attnum)
    ) as ddl
  from column_ddl
  group by nspname, relname
),
constraint_ddl as (
  select
    case when con.contype = 'f' then 50 else 40 end as section_order,
    format('%I.%I.%I', n.nspname, c.relname, con.conname) as object_key,
    format(
      E'alter table only %I.%I add constraint %I %s;\n',
      n.nspname,
      c.relname,
      con.conname,
      pg_get_constraintdef(con.oid, true)
    ) as ddl
  from pg_constraint con
  join pg_class c on c.oid = con.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and con.contype in ('c', 'f', 'p', 'u', 'x')
),
sequence_owner_ddl as (
  select
    55 as section_order,
    format('%I.%I', sn.nspname, seq.relname) as object_key,
    format(
      E'alter sequence %I.%I owned by %I.%I.%I;\n',
      sn.nspname,
      seq.relname,
      tn.nspname,
      tab.relname,
      att.attname
    ) as ddl
  from pg_class seq
  join pg_namespace sn on sn.oid = seq.relnamespace
  join pg_depend dep
    on dep.classid = 'pg_class'::regclass
   and dep.objid = seq.oid
   and dep.refclassid = 'pg_class'::regclass
   and dep.deptype = 'a'
  join pg_class tab on tab.oid = dep.refobjid
  join pg_namespace tn on tn.oid = tab.relnamespace
  join pg_attribute att on att.attrelid = tab.oid and att.attnum = dep.refobjsubid
  cross join scope
  where sn.nspname = any(scope.owned_schemas)
    and seq.relkind = 'S'
),
index_ddl as (
  select
    60 as section_order,
    format('%I.%I', ni.nspname, ic.relname) as object_key,
    pg_get_indexdef(i.indexrelid) || E';\n' as ddl
  from pg_index i
  join pg_class tc on tc.oid = i.indrelid
  join pg_namespace nt on nt.oid = tc.relnamespace
  join pg_class ic on ic.oid = i.indexrelid
  join pg_namespace ni on ni.oid = ic.relnamespace
  left join pg_constraint con on con.conindid = i.indexrelid
  cross join scope
  where nt.nspname = any(scope.owned_schemas)
    and con.oid is null
),
function_ddl as (
  select
    70 as section_order,
    format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) as object_key,
    pg_get_functiondef(p.oid) || E';\n' as ddl
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and not exists (select 1 from pre_table_function_oids required where required.oid = p.oid)
),
view_ddl as (
  select
    80 as section_order,
    format('%I.%I', n.nspname, c.relname) as object_key,
    format(
      E'create view %I.%I%s as\n%s;\n',
      n.nspname,
      c.relname,
      case
        when c.reloptions is null then ''
        else format(' with (%s)', array_to_string(c.reloptions, ', '))
      end,
      pg_get_viewdef(c.oid, true)
    ) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and c.relkind = 'v'
),
trigger_ddl as (
  select
    90 as section_order,
    format('%I.%I.%I', n.nspname, c.relname, t.tgname) as object_key,
    regexp_replace(
      pg_get_triggerdef(t.oid, false),
      E'EXECUTE FUNCTION [^(]+\\(',
      format('EXECUTE FUNCTION %I.%I(', function_namespace.nspname, function_proc.proname)
    ) || E';\n' as ddl
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  join pg_proc function_proc on function_proc.oid = t.tgfoid
  join pg_namespace function_namespace on function_namespace.oid = function_proc.pronamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and not t.tgisinternal
),
rls_ddl as (
  select
    100 as section_order,
    format('%I.%I', n.nspname, c.relname) as object_key,
    format(
      E'alter table %I.%I enable row level security;%s\n',
      n.nspname,
      c.relname,
      case when c.relforcerowsecurity
        then format(E'\nalter table %I.%I force row level security;', n.nspname, c.relname)
        else ''
      end
    ) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname in ('public', 'private')
    and c.relkind in ('r', 'p')
    and c.relrowsecurity
),
policy_ddl as (
  select
    110 as section_order,
    format('%I.%I.%I', n.nspname, c.relname, p.polname) as object_key,
    format(
      E'drop policy if exists %I on %I.%I;\ncreate policy %I on %I.%I as %s for %s to %s%s%s;\n',
      p.polname,
      n.nspname,
      c.relname,
      p.polname,
      n.nspname,
      c.relname,
      case when p.polpermissive then 'permissive' else 'restrictive' end,
      case p.polcmd when '*' then 'all' when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update' when 'd' then 'delete' end,
      (
        select string_agg(case when role_oid = 0 then 'public' else quote_ident(r.rolname) end, ', ' order by role_oid)
        from unnest(p.polroles) role_oid
        left join pg_roles r on r.oid = role_oid
      ),
      case when p.polqual is not null then format(' using (%s)', pg_get_expr(p.polqual, p.polrelid)) else '' end,
      case when p.polwithcheck is not null then format(' with check (%s)', pg_get_expr(p.polwithcheck, p.polrelid)) else '' end
    ) as ddl
  from pg_policy p
  join pg_class c on c.oid = p.polrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname in ('public', 'private', 'storage')
),
relation_acl_target as (
  select
    c.oid,
    c.relkind,
    n.nspname,
    c.relname,
    c.relowner,
    coalesce(c.relacl, acldefault(
      case when c.relkind = 'S' then 'S'::"char" else 'r'::"char" end,
      c.relowner
    )) as acl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
    and c.relkind in ('r', 'p', 'v', 'S')
),
relation_acl_ddl as (
  select
    120 as section_order,
    format('%I.%I.%s.%s', t.nspname, t.relname, x.grantee, x.privilege_type) as object_key,
    format(
      E'grant %s on %s %I.%I to %s%s;\n',
      x.privilege_type,
      case when t.relkind = 'S' then 'sequence' else 'table' end,
      t.nspname,
      t.relname,
      case when x.grantee = 0 then 'public' else quote_ident(r.rolname) end,
      case when x.is_grantable then ' with grant option' else '' end
    ) as ddl
  from relation_acl_target t
  cross join lateral aclexplode(t.acl) x
  left join pg_roles r on r.oid = x.grantee
  where x.grantee <> t.relowner
),
function_acl_target as (
  select
    p.oid,
    n.nspname,
    p.proname,
    p.proowner,
    pg_get_function_identity_arguments(p.oid) as args,
    coalesce(p.proacl, acldefault('f', p.proowner)) as acl
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
),
function_revoke_ddl as (
  select
    125 as section_order,
    format('%I.%I(%s)', nspname, proname, args) as object_key,
    format(E'revoke all on function %I.%I(%s) from public;\n', nspname, proname, args) as ddl
  from function_acl_target
),
function_acl_ddl as (
  select
    130 as section_order,
    format('%I.%I(%s).%s.%s', t.nspname, t.proname, t.args, x.grantee, x.privilege_type) as object_key,
    format(
      E'grant %s on function %I.%I(%s) to %s%s;\n',
      x.privilege_type,
      t.nspname,
      t.proname,
      t.args,
      case when x.grantee = 0 then 'public' else quote_ident(r.rolname) end,
      case when x.is_grantable then ' with grant option' else '' end
    ) as ddl
  from function_acl_target t
  cross join lateral aclexplode(t.acl) x
  left join pg_roles r on r.oid = x.grantee
  where x.grantee <> t.proowner
),
publication_ddl as (
  select
    140 as section_order,
    format('%I.%I', n.nspname, c.relname) as object_key,
    format(
      E'do $baseline$ begin\n  if exists (select 1 from pg_publication where pubname = %L) then\n    alter publication %I add table %I.%I;\n  end if;\nexception when duplicate_object then null;\nend $baseline$;\n',
      pub.pubname,
      pub.pubname,
      n.nspname,
      c.relname
    ) as ddl
  from pg_publication_rel pr
  join pg_publication pub on pub.oid = pr.prpubid
  join pg_class c on c.oid = pr.prrelid
  join pg_namespace n on n.oid = c.relnamespace
  cross join scope
  where n.nspname = any(scope.owned_schemas)
),
all_ddl as (
  select 0 as section_order, '000-header' as object_key,
    E'-- SANAD canonical schema-only baseline\n-- Generated from PostgreSQL catalogs; contains no table rows.\n-- Staged outside supabase/migrations: activation requires the separately reviewed ledger cutover.\nset check_function_bodies = false;\ncreate extension if not exists pgcrypto with schema extensions;\ncreate extension if not exists "uuid-ossp" with schema extensions;\ncreate extension if not exists pg_net with schema extensions;\ncreate extension if not exists pg_cron;\ncreate extension if not exists supabase_vault with schema vault;\ncreate schema if not exists app;\ncreate schema if not exists private;\n\n' as ddl
  union all select * from sequence_ddl
  union all select * from pre_table_function_ddl
  union all select * from table_ddl
  union all select * from constraint_ddl
  union all select * from sequence_owner_ddl
  union all select * from index_ddl
  union all select * from function_ddl
  union all select * from view_ddl
  union all select * from trigger_ddl
  union all select * from rls_ddl
  union all select * from policy_ddl
  union all select * from relation_acl_ddl
  union all select * from function_revoke_ddl
  union all select * from function_acl_ddl
  union all select * from publication_ddl
  union all select 999, '999-footer', E'\nreset check_function_bodies;\n' as ddl
),
document as (
  select string_agg(ddl, E'\n' order by section_order, object_key) as body
  from all_ddl
),
chunks as (
  select
    n as chunk_no,
    substr(body, ((n - 1) * 30000) + 1, 30000) as body_chunk
  from document
  cross join lateral generate_series(1, ceil(length(body) / 30000.0)::integer) n
)
select
  chunk_no,
  encode(convert_to(body_chunk, 'UTF8'), 'base64') as content_base64
from chunks
order by chunk_no;
