import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import {
  CheckCircle2, Clock3, ExternalLink, FileText, History, Inbox, Loader2,
  Maximize2, RefreshCw, ShieldCheck, X, ZoomIn, ZoomOut
} from 'lucide-react';
import FinancialEntityLogo from '../../components/FinancialEntityLogo';
import { supabase } from '../../lib/supabase';
import { requestOperationFileAccess } from '../../lib/operationFileAccess';
import { claimPaymentInboxItem, type PaymentInboxItem } from '../../lib/paymentInboxApi';
import { toLatinDigits } from '../../lib/digits';

type Tab='operation'|'document'|'record';
type PreviewState='idle'|'pending'|'ready'|'failed';
type Runtime={
 contract_version:number;read_only:boolean;
 operation:{id:string;public_token:string;status?:string|null;ai_status?:string|null;financial_entity?:string|null;financial_entity_code?:string|null;amount?:number|string|null;currency?:string|null;receiver_name?:string|null;receiver_name_raw?:string|null;receiver_account?:string|null;reference_number?:string|null;summary?:string|null;confidence_score?:number|null;risk_level?:string|null;review_status?:string|null;warnings?:unknown[];attention_points?:unknown[]};
 timing:{transaction_at?:string|null;transaction_date_source?:string|null;transaction_time_present?:boolean;transaction_timezone?:string|null;received_at?:string|null;received_timezone?:string|null;delta_seconds?:number|null};
 document:{original_mime_type?:string|null;original_name?:string|null;original_size?:number|null;original_status?:string|null;preview_status?:string|null;preview_mime_type?:string|null;preview_size?:number|null;preview_width?:number|null;preview_height?:number|null;preview_generated_at?:string|null;preview_error?:string|null;preview_attempt_count?:number|null;preview_pipeline_version?:string|null};
 inbox?:null|{id:string;business_id:string;business_name?:string|null;financial_account_id?:string|null;financial_account_holder?:string|null;financial_account_verification?:string|null;status:string;row_version:number;priority?:number|null;match_score?:number|null;match_strategy?:string|null;claimed_by_user_id?:string|null;claimed_by_name?:string|null;claimed_at?:string|null;completed_by_user_id?:string|null;completed_by_name?:string|null;completed_at?:string|null;review_reason?:string|null;is_mine?:boolean;is_supervisor?:boolean;permissions?:{can_view?:boolean;can_claim?:boolean;can_complete?:boolean;can_review?:boolean;can_release?:boolean}};
 verification:{verified_by_user_id?:string|null;verified_by_name?:string|null;verified_at?:string|null;verification_note?:string|null};
};
type PreviewResponse={ok?:boolean;status?:string;available?:boolean;signed_url?:string;retry_after_seconds?:number;width?:number|null;height?:number|null};

const TOKEN_PATTERN=/\/v\/([0-9a-fA-F-]{36})(?:\/|$)/;
function currentToken(){return window.location.pathname.match(TOKEN_PATTERN)?.[1]||null;}
function fmt(value?:string|null){if(!value)return 'غير متوفر';const d=new Date(value);if(Number.isNaN(d.getTime()))return 'غير متوفر';return toLatinDigits(new Intl.DateTimeFormat('ar-YE',{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d));}
function fmtBytes(value?:number|null){if(!value)return null;if(value<1024)return `${value} B`;if(value<1048576)return `${Math.round(value/1024)} KB`;return `${(value/1048576).toFixed(1)} MB`;}
function delayLabel(seconds?:number|null){if(seconds===null||seconds===undefined)return null;const abs=Math.abs(seconds);const before=seconds<0;const suffix=before?'قبل وقت العملية المستخرج':'بعد العملية';if(abs<60)return 'وصل إلى سند في الوقت نفسه تقريبًا';if(abs<3600)return `وصل إلى سند ${suffix} بـ ${toLatinDigits(String(Math.round(abs/60)))} دقيقة`;if(abs<86400)return `وصل إلى سند ${suffix} بـ ${toLatinDigits(String(Math.round(abs/3600)))} ساعة`;return `وصل إلى سند ${suffix} بـ ${toLatinDigits(String(Math.round(abs/86400)))} يوم`;}
function statusMeta(status?:string|null){if(status==='new'||status==='released')return['جديدة','bg-blue-50 text-blue-700 border-blue-100'];if(status==='claimed')return['قيد المعالجة','bg-amber-50 text-amber-800 border-amber-100'];if(status==='review_required')return['تحتاج مراجعة','bg-orange-50 text-orange-800 border-orange-100'];if(status==='completed')return['مكتملة','bg-emerald-50 text-emerald-700 border-emerald-100'];if(status==='rejected')return['مرفوضة','bg-rose-50 text-rose-700 border-rose-100'];return['للاطلاع','bg-slate-50 text-slate-600 border-slate-100'];}
function validRuntime(value:any):value is Runtime{return Boolean(value&&value.contract_version>=2&&value.read_only===true&&value.operation?.id&&value.operation?.public_token&&value.timing&&value.document&&value.verification);}

export default function OperationDetailsRuntimeV2(){
 const [token,setToken]=useState<string|null>(()=>currentToken());
 const [runtime,setRuntime]=useState<Runtime|null>(null);
 const [host,setHost]=useState<HTMLElement|null>(null);
 const [tab,setTab]=useState<Tab>('operation');
 const [error,setError]=useState<string|null>(null);
 const [message,setMessage]=useState<string|null>(null);
 const [acting,setActing]=useState(false);
 const [originalUrl,setOriginalUrl]=useState<string|null>(null);
 const [previewUrl,setPreviewUrl]=useState<string|null>(null);
 const [previewState,setPreviewState]=useState<PreviewState>('idle');
 const [fullscreen,setFullscreen]=useState(false);
 const [zoom,setZoom]=useState(1);
 const hiddenRef=useRef(new Map<HTMLElement,string>());

 useEffect(()=>{const id=window.setInterval(()=>setToken(v=>currentToken()===v?v:currentToken()),350);return()=>window.clearInterval(id);},[]);

 const load=useCallback(async()=>{
  if(!token)return;setError(null);setRuntime(null);
  try{
   const {data:access,error:accessError}=await supabase.rpc('open_operation_access',{p_public_token:token,p_source:'app'});
   if(accessError||!access?.allowed)throw accessError||new Error('تعذر فتح العملية.');
   const {data,error:runtimeError}=await supabase.rpc('get_operation_details_runtime',{p_public_token:token});
   if(runtimeError)throw runtimeError;if(!validRuntime(data))throw new Error('عقد تفاصيل العملية غير مكتمل.');
   setRuntime(data);
   const original=await requestOperationFileAccess(token,'open').catch(()=>null);setOriginalUrl(original?.signedUrl||null);
  }catch(cause){console.error('OperationDetailsRuntimeV2 load failed',cause);setError(cause instanceof Error?cause.message:'تعذر تجهيز تفاصيل العملية.');}
 },[token]);
 useEffect(()=>{void load();},[load]);

 useEffect(()=>{
  if(!runtime)return;let disposed=false;
  const attach=()=>{if(disposed)return;const details=document.getElementById('details_view');if(!details)return;let mount=document.getElementById('operation_details_runtime_v2_mount');if(!(mount instanceof HTMLElement)){mount=document.createElement('div');mount.id='operation_details_runtime_v2_mount';details.prepend(mount);}Array.from(details.children).forEach(child=>{if(!(child instanceof HTMLElement)||child===mount)return;if(!hiddenRef.current.has(child))hiddenRef.current.set(child,child.style.display);child.style.display='none';});details.dataset.operationRuntimeV2='active';setHost(mount);};
  attach();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});const timer=window.setInterval(attach,500);
  return()=>{disposed=true;observer.disconnect();window.clearInterval(timer);hiddenRef.current.forEach((display,node)=>{node.style.display=display;});hiddenRef.current.clear();document.getElementById('operation_details_runtime_v2_mount')?.remove();document.getElementById('details_view')?.removeAttribute('data-operation-runtime-v2');};
 },[runtime]);

 useEffect(()=>{
  if(!token||!runtime)return;let cancelled=false;let timer:number|undefined;const started=Date.now();
  const poll=async()=>{const {data,error:previewError}=await supabase.functions.invoke<PreviewResponse>('sanad-operation-preview-access',{body:{public_token:token,request_processing:true}});if(cancelled)return;if(!previewError&&data?.available&&data.signed_url){setPreviewUrl(data.signed_url);setPreviewState('ready');return;}if(previewError||data?.status==='failed'||Date.now()-started>30000){setPreviewState('failed');return;}setPreviewState('pending');timer=window.setTimeout(poll,Math.max(4000,Number(data?.retry_after_seconds||6)*1000));};setPreviewState('pending');void poll();return()=>{cancelled=true;if(timer)window.clearTimeout(timer);};
 },[token,runtime?.operation.id]);

 const refresh=useCallback(async()=>{if(!token)return;const {data,error:e}=await supabase.rpc('get_operation_details_runtime',{p_public_token:token});if(e)throw e;if(!validRuntime(data))throw new Error('تعذر تحديث الحالة.');setRuntime(data);},[token]);
 const claim=async()=>{if(!runtime?.inbox)return;setActing(true);setError(null);setMessage(null);try{await claimPaymentInboxItem({id:runtime.inbox.id,operation_id:runtime.operation.id,public_token:runtime.operation.public_token,business_id:runtime.inbox.business_id,status:runtime.inbox.status,row_version:runtime.inbox.row_version} as PaymentInboxItem);await refresh();setMessage('تم استلام العملية وستبقى مسندة إليك حتى إجراء صريح.');}catch(c){setError(c instanceof Error?c.message:'تعذر استلام العملية.');}finally{setActing(false);}};
 const complete=async()=>{if(!runtime?.inbox||!token)return;setActing(true);setError(null);setMessage(null);try{const {data,error:e}=await supabase.rpc('complete_operation_workflow',{p_operation_id:runtime.operation.id,p_token:token,p_business_id:runtime.inbox.business_id,p_inbox_id:runtime.inbox.id,p_note:null,p_source:'operation_details_runtime_v2'});if(e)throw e;if(data&&typeof data==='object'&&(data as any).ok===false)throw new Error('تغيرت حالة العملية قبل تنفيذ الاعتماد.');await refresh();setMessage('تم اعتماد العملية وتحديث سجل وارد المدفوعات باسمك.');}catch(c){setError(c instanceof Error?c.message:'تعذر اعتماد العملية.');}finally{setActing(false);}};
 const personalVerify=async()=>{if(!token)return;setActing(true);setError(null);setMessage(null);try{const {error:e}=await supabase.rpc('verify_operation',{p_token:token,p_note:null});if(e)throw e;await refresh();setMessage('تم تسجيل تحققك الشخصي دون تغيير حالة وارد المدفوعات.');}catch(c){setError(c instanceof Error?c.message:'تعذر تسجيل التحقق.');}finally{setActing(false);}};
 const retryPreview=async()=>{if(!runtime)return;setPreviewState('pending');setPreviewUrl(null);const {error:e}=await supabase.rpc('requeue_operation_preview_v2',{p_operation_id:runtime.operation.id});if(e){setPreviewState('failed');setError(e.message);return;}await supabase.functions.invoke('sanad-operation-preview-worker',{body:{}}).catch(()=>null);};

 const inboxUrl=useMemo(()=>{if(!runtime?.inbox)return null;const admin=runtime.inbox.status==='review_required'&&runtime.inbox.is_supervisor;const q=new URLSearchParams({view:admin?'payment-inbox-admin':'payment-inbox',business_id:runtime.inbox.business_id,operation_id:runtime.operation.id});return `/business/manage/operations?${q}`;},[runtime]);
 if(!runtime||!host)return null;
 const [statusLabel,statusClass]=statusMeta(runtime.inbox?.status);const lag=delayLabel(runtime.timing.delta_seconds);const entity=runtime.operation.financial_entity||'جهة مالية أخرى';const amount=runtime.operation.amount??'—';const currency=runtime.operation.currency||'—';const mime=runtime.document.original_mime_type||'application/pdf';const documentUrl=previewState==='ready'&&previewUrl?previewUrl:originalUrl;
 const action=runtime.inbox?<div className="grid grid-cols-2 gap-2">{runtime.inbox.permissions?.can_claim?<button onClick={()=>void claim()} disabled={acting} className="h-12 rounded-2xl border border-slate-200 bg-white text-xs font-black text-slate-800 disabled:opacity-50">استلام العملية</button>:null}{runtime.inbox.permissions?.can_complete?<button onClick={()=>void complete()} disabled={acting} className="h-12 rounded-2xl bg-emerald-600 text-xs font-black text-white shadow-lg shadow-emerald-600/20 disabled:opacity-50">{acting?'جارٍ التنفيذ...':'اعتماد العملية'}</button>:null}{runtime.inbox.status==='review_required'&&inboxUrl?<a href={inboxUrl} className="col-span-2 flex h-12 items-center justify-center rounded-2xl bg-amber-600 text-xs font-black text-white">مراجعة العملية في وارد المدفوعات</a>:null}{runtime.inbox.status==='completed'?<div className="col-span-2 flex h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-50 text-xs font-black text-emerald-700"><CheckCircle2 className="h-4 w-4"/>اعتمدها {runtime.inbox.completed_by_name||'عضو الفريق'}</div>:null}</div>:<button onClick={()=>void personalVerify()} disabled={acting} className="h-12 w-full rounded-2xl bg-emerald-600 text-xs font-black text-white disabled:opacity-50">تسجيل تحقق شخصي</button>;

 return <>{createPortal(<section dir="rtl" className="mx-auto max-w-2xl space-y-3 pb-36 font-arabic">
  <div className="flex items-center justify-between gap-3 px-1 text-[10px] text-slate-500"><span className="inline-flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5"/>وصل إلى سند: <b className="text-slate-700">{fmt(runtime.timing.received_at)}</b></span><span className={`rounded-full border px-2.5 py-1 font-black ${statusClass}`}>{statusLabel}</span></div>
  <article className="rounded-[28px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><FinancialEntityLogo entity={entity} className="h-12 w-12 rounded-2xl border border-slate-100"/><div className="min-w-0 flex-1"><p className="text-[10px] font-bold text-slate-400">الجهة المالية</p><h1 className="truncate text-base font-black text-slate-950">{entity}</h1></div><div className="text-left"><strong className="block text-4xl font-black tracking-tight text-slate-950">{amount}</strong><span className="text-[10px] font-black text-emerald-700">{currency}</span></div></div>
   <div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 border-t border-slate-100 pt-4 text-[11px]"><div className="col-span-2"><span className="block text-slate-400">المستلم</span><b className="mt-1 block text-sm text-slate-900">{runtime.operation.receiver_name||'غير متوفر'}</b></div><div><span className="block text-slate-400">رقم الحساب</span><b dir="ltr" className="mt-1 block font-mono text-slate-800">{runtime.operation.receiver_account?toLatinDigits(String(runtime.operation.receiver_account)):'—'}</b></div><div><span className="block text-slate-400">المرجع</span><b dir="ltr" className="mt-1 block font-mono text-slate-800">{runtime.operation.reference_number?toLatinDigits(String(runtime.operation.reference_number)):'—'}</b></div><div className="col-span-2 rounded-2xl bg-slate-50 px-3 py-2.5"><span className="block text-slate-400">وقت العملية بحسب الإشعار الأصلي</span><b className="mt-1 block text-sm text-slate-900">{fmt(runtime.timing.transaction_at)}</b>{lag?<span className="mt-1 block text-[10px] text-slate-500">{lag}</span>:null}</div></div>
  </article>
  <nav className="grid grid-cols-3 rounded-2xl border border-slate-200 bg-slate-100 p-1">{([['operation','العملية'],['document','المستند'],['record','السجل']] as Array<[Tab,string]>).map(([value,label])=><button key={value} onClick={()=>setTab(value)} className={`h-10 rounded-xl text-[11px] font-black ${tab===value?'bg-white text-slate-950 shadow-sm':'text-slate-500'}`}>{label}</button>)}</nav>
  {error?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-[11px] leading-5 text-rose-700">{error}</div>:null}{message?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-[11px] leading-5 text-emerald-800">{message}</div>:null}
  {tab==='operation'?<div className="space-y-3"><section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/><div><h2 className="text-sm font-black text-slate-900">حالة المطابقة والتشغيل</h2><p className="mt-1 text-[11px] leading-6 text-slate-500">فتح الصفحة أو المستند لا يغير حالة العملية. تتغير الحالة فقط عند تنفيذ إجراء صريح.</p></div></div>{runtime.inbox?<div className="mt-3 rounded-2xl bg-slate-50 p-3 text-[11px] leading-6 text-slate-600"><b className="text-slate-900">{runtime.inbox.business_name}</b><br/>الحالة الحالية: {statusLabel}{runtime.inbox.claimed_by_name?` · المسؤول: ${runtime.inbox.claimed_by_name}`:''}</div>:<div className="mt-3 rounded-2xl bg-slate-50 p-3 text-[11px] text-slate-600">هذه العملية ليست مرتبطة حاليًا بوارد نشاط يمكنك تشغيله.</div>}</section>{inboxUrl?<a href={inboxUrl} className="flex h-12 items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white text-xs font-black text-slate-800"><Inbox className="h-4 w-4"/>فتح وارد المدفوعات</a>:null}</div>:null}
  {tab==='document'?<section className="rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><div className="mb-3 flex items-center justify-between px-1"><div><h2 className="text-sm font-black text-slate-900">المستند المالي</h2><p className="text-[9px] text-slate-400">الأصل محفوظ دون تعديل</p></div><span className="text-[9px] font-bold text-slate-400">{previewState==='ready'?'معاينة محسّنة':'الأصل'}</span></div>{documentUrl?<button onClick={()=>setFullscreen(true)} className="relative block w-full overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex min-h-[220px] items-center justify-center bg-white">{previewState==='ready'||!mime.includes('pdf')?<img src={documentUrl} alt="معاينة المستند" className="block h-auto max-h-[62dvh] w-full object-contain"/>:<iframe src={documentUrl} title="المستند الأصلي" className="h-[460px] w-full bg-white"/>}</div><span className="absolute bottom-3 left-3 inline-flex items-center gap-1.5 rounded-xl bg-slate-950/80 px-3 py-2 text-[10px] font-bold text-white"><Maximize2 className="h-3.5 w-3.5"/>تكبير</span></button>:<div className="flex min-h-[260px] items-center justify-center rounded-2xl bg-slate-50"><Loader2 className="h-6 w-6 animate-spin text-slate-400"/></div>}{previewState==='pending'?<p className="mt-3 text-center text-[10px] text-slate-500">تُجهّز معاينة مركزة، بينما يبقى المستند الأصلي متاحًا.</p>:null}{previewState==='failed'?<div className="mt-3 flex items-center justify-between gap-2 rounded-2xl bg-slate-50 p-3 text-[10px] text-slate-500"><span>تعذر إعداد المعاينة المحسنة؛ يعرض سند الأصل.</span><button onClick={()=>void retryPreview()} className="inline-flex items-center gap-1 font-black text-slate-700"><RefreshCw className="h-3.5 w-3.5"/>إعادة المحاولة</button></div>:null}<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setFullscreen(true)} className="h-11 rounded-2xl border border-slate-200 text-[11px] font-black text-slate-700">تكبير المعاينة</button>{originalUrl?<a href={originalUrl} target="_blank" rel="noreferrer" className="flex h-11 items-center justify-center gap-1.5 rounded-2xl bg-emerald-600 text-[11px] font-black text-white"><ExternalLink className="h-3.5 w-3.5"/>فتح الأصل</a>:null}</div><div className="mt-2 px-1 text-[9px] text-slate-400">{[runtime.document.preview_pipeline_version,fmtBytes(runtime.document.preview_size)].filter(Boolean).join(' · ')}</div></section>:null}
  {tab==='record'?<section className="space-y-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><History className="h-5 w-5 text-slate-500"/><h2 className="text-sm font-black text-slate-900">سجل العملية</h2></div><div className="grid gap-2 text-[11px]"><div className="rounded-2xl bg-slate-50 p-3"><span className="text-slate-400">وقت الإدخال إلى سند</span><b className="mt-1 block text-slate-900">{fmt(runtime.timing.received_at)}</b></div><div className="rounded-2xl bg-slate-50 p-3"><span className="text-slate-400">وقت العملية المستخرج</span><b className="mt-1 block text-slate-900">{fmt(runtime.timing.transaction_at)}</b></div><div className="rounded-2xl border border-slate-100 p-3"><span className="text-slate-400">التحقق</span><b className="mt-1 block text-slate-900">{runtime.verification.verified_by_name?`تحقق ${runtime.verification.verified_by_name}`:'لم يسجل تحقق شخصي بعد'}</b>{runtime.verification.verified_at?<span className="mt-1 block text-slate-500">{fmt(runtime.verification.verified_at)}</span>:null}</div></div></section>:null}
 </section>,host)}
 {createPortal(<div dir="rtl" className="fixed inset-x-0 bottom-[calc(68px+env(safe-area-inset-bottom))] z-[135] mx-auto max-w-2xl px-3"><div className="rounded-[24px] border border-slate-200 bg-white/95 p-3 shadow-[0_-12px_35px_rgba(15,23,42,.12)] backdrop-blur">{action}</div></div>,document.body)}
 {fullscreen&&documentUrl?createPortal(<div className="fixed inset-0 z-[220] flex flex-col bg-black/95" dir="rtl"><div className="flex items-center justify-between px-4 pb-3 pt-[calc(12px+env(safe-area-inset-top))] text-white"><div><p className="text-sm font-bold">معاينة المستند</p><p className="text-[10px] text-white/60">{previewState==='ready'?'نسخة محسّنة مركزة':'المستند الأصلي'}</p></div><button onClick={()=>setFullscreen(false)} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10"><X className="h-5 w-5"/></button></div><div className="min-h-0 flex-1 overflow-auto px-3 py-2"><div className="flex min-h-full items-center justify-center">{previewState==='ready'||!mime.includes('pdf')?<img src={documentUrl} alt="المستند" className="max-w-none origin-center object-contain transition-transform" style={{width:`${Math.max(100,zoom*100)}%`,transform:`scale(${zoom})`}}/>:<iframe src={documentUrl} title="المستند الأصلي" className="h-full min-h-[80dvh] w-full bg-white"/>}</div></div>{previewState==='ready'||!mime.includes('pdf')?<div className="flex items-center justify-center gap-3 border-t border-white/10 bg-black/80 px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3"><button onClick={()=>setZoom(v=>Math.max(.75,v-.25))} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white"><ZoomOut className="h-5 w-5"/></button><span className="min-w-16 text-center text-xs font-bold text-white">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(v=>Math.min(3,v+.25))} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/10 text-white"><ZoomIn className="h-5 w-5"/></button></div>:null}</div>,document.body):null}
 </>;
}
