-- SANAD admin-managed public business slugs.

create table if not exists public.business_slug_admin_audit (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.business_profiles(id) on delete cascade,
  previous_slug text not null,
  new_slug text not null,
  reason text not null,
  actor_user_id uuid not null,
  created_at timestamptz not null default now()
);

alter table public.business_slug_admin_audit enable row level security;

create index if not exists business_slug_admin_audit_business_created_idx
  on public.business_slug_admin_audit (business_id, created_at desc);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'business_profiles_published_slug_ready_check'
      and conrelid = 'public.business_profiles'::regclass
  ) then
    alter table public.business_profiles
      add constraint business_profiles_published_slug_ready_check
      check (
        public_status <> 'published'
        or (
          slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
          and slug !~ '^pending-'
          and length(slug) between 3 and 80
        )
      ) not valid;
  end if;
end $$;

create or replace function public.platform_admin_set_business_slug(
  p_business_id uuid,
  p_slug text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_uid uuid := auth.uid();
  v_slug text := lower(trim(coalesce(p_slug, '')));
  v_reason text := trim(coalesce(p_reason, ''));
  v_previous_slug text;
  v_business_name text;
  v_public_status text;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  if not public.is_platform_admin(v_uid) then raise exception 'platform_admin_required'; end if;
  if length(v_reason) < 5 then raise exception 'admin_reason_required'; end if;
  if length(v_slug) < 3 or length(v_slug) > 80 then raise exception 'invalid_business_slug_length'; end if;
  if v_slug !~ '^[a-z0-9]+(-[a-z0-9]+)*$' then raise exception 'invalid_business_slug_format'; end if;
  if v_slug ~ '^pending-' or v_slug in ('admin','api','app','auth','business','help','login','profile','sanad','settings','support','verify','www') then
    raise exception 'reserved_business_slug';
  end if;

  select slug, name, public_status
  into v_previous_slug, v_business_name, v_public_status
  from public.business_profiles
  where id = p_business_id
  for update;

  if not found then raise exception 'business_not_found'; end if;
  if exists (select 1 from public.business_profiles where slug = v_slug and id <> p_business_id) then
    raise exception 'business_slug_already_used';
  end if;

  if v_previous_slug <> v_slug then
    update public.business_profiles set slug = v_slug, updated_at = now() where id = p_business_id;
    insert into public.business_slug_admin_audit (business_id, previous_slug, new_slug, reason, actor_user_id)
    values (p_business_id, v_previous_slug, v_slug, v_reason, v_uid);
  end if;

  return jsonb_build_object(
    'ok', true,
    'business_id', p_business_id,
    'business_name', v_business_name,
    'previous_slug', v_previous_slug,
    'slug', v_slug,
    'public_status', v_public_status,
    'public_url', 'https://app.sanadflow.com/b/' || v_slug
  );
end;
$function$;

revoke all on function public.platform_admin_set_business_slug(uuid,text,text) from public;
grant execute on function public.platform_admin_set_business_slug(uuid,text,text) to authenticated;
