create table if not exists public.ai_model_pricing (
  model text not null,
  billing_mode text not null default 'standard',
  input_per_million_usd numeric(12,6) not null,
  cached_input_per_million_usd numeric(12,6),
  output_per_million_usd numeric(12,6) not null,
  effective_from timestamptz not null default now(),
  effective_to timestamptz,
  source_url text,
  notes text,
  primary key (model, billing_mode, effective_from)
);

alter table public.ai_model_pricing enable row level security;
revoke all on public.ai_model_pricing from anon, authenticated;

create table if not exists public.ai_usage_ledger (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  request_id text,
  operation_id uuid references public.operations(id) on delete set null,
  source text not null,
  purpose text not null,
  environment text not null default 'production',
  model text not null,
  billing_mode text not null default 'standard',
  status text not null default 'completed',
  prompt_tokens bigint not null default 0,
  cached_tokens bigint not null default 0,
  candidate_tokens bigint not null default 0,
  thinking_tokens bigint not null default 0,
  billed_output_tokens bigint generated always as (candidate_tokens + thinking_tokens) stored,
  total_tokens bigint not null default 0,
  input_cost_usd numeric(18,9) not null default 0,
  cached_input_cost_usd numeric(18,9) not null default 0,
  output_cost_usd numeric(18,9) not null default 0,
  estimated_cost_usd numeric(18,9) generated always as (input_cost_usd + cached_input_cost_usd + output_cost_usd) stored,
  latency_ms integer,
  usage_metadata jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists ai_usage_ledger_request_id_uidx on public.ai_usage_ledger(request_id) where request_id is not null;
create index if not exists ai_usage_ledger_occurred_at_idx on public.ai_usage_ledger(occurred_at desc);
create index if not exists ai_usage_ledger_operation_id_idx on public.ai_usage_ledger(operation_id);
create index if not exists ai_usage_ledger_purpose_idx on public.ai_usage_ledger(purpose, occurred_at desc);

alter table public.ai_usage_ledger enable row level security;
revoke all on public.ai_usage_ledger from anon, authenticated;

insert into public.ai_model_pricing(model,billing_mode,input_per_million_usd,cached_input_per_million_usd,output_per_million_usd,effective_from,source_url,notes)
values
('gemini-3.5-flash-lite','standard',0.30,0.03,2.50,'2026-08-01T00:00:00Z','https://ai.google.dev/gemini-api/docs/pricing','Google AI Developer API standard pricing; output includes thinking tokens'),
('gemini-2.5-flash','standard',0.30,0.03,2.50,'2026-08-01T00:00:00Z','https://ai.google.dev/gemini-api/docs/pricing','Google AI Developer API standard pricing; output includes thinking tokens'),
('gemini-2.5-flash-lite','standard',0.10,0.01,0.40,'2026-08-01T00:00:00Z','https://ai.google.dev/gemini-api/docs/pricing','Google AI Developer API standard pricing; output includes thinking tokens')
on conflict do nothing;

create or replace function public.record_ai_usage(
  p_request_id text,
  p_operation_id uuid,
  p_source text,
  p_purpose text,
  p_model text,
  p_billing_mode text,
  p_status text,
  p_latency_ms integer,
  p_usage_metadata jsonb,
  p_metadata jsonb default '{}'::jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prompt bigint := coalesce((p_usage_metadata->>'promptTokenCount')::bigint,0);
  v_cached bigint := coalesce((p_usage_metadata->>'cachedContentTokenCount')::bigint,0);
  v_candidate bigint := coalesce((p_usage_metadata->>'candidatesTokenCount')::bigint,0);
  v_thinking bigint := coalesce((p_usage_metadata->>'thoughtsTokenCount')::bigint,0);
  v_total bigint := coalesce((p_usage_metadata->>'totalTokenCount')::bigint,0);
  v_price public.ai_model_pricing%rowtype;
  v_id bigint;
begin
  select * into v_price
  from public.ai_model_pricing
  where model=p_model and billing_mode=coalesce(nullif(p_billing_mode,''),'standard')
    and effective_from <= now()
    and (effective_to is null or effective_to > now())
  order by effective_from desc limit 1;

  insert into public.ai_usage_ledger(
    request_id,operation_id,source,purpose,model,billing_mode,status,latency_ms,
    prompt_tokens,cached_tokens,candidate_tokens,thinking_tokens,total_tokens,
    input_cost_usd,cached_input_cost_usd,output_cost_usd,usage_metadata,metadata
  ) values (
    p_request_id,p_operation_id,p_source,p_purpose,p_model,coalesce(nullif(p_billing_mode,''),'standard'),coalesce(nullif(p_status,''),'completed'),p_latency_ms,
    v_prompt,v_cached,v_candidate,v_thinking,v_total,
    greatest(v_prompt-v_cached,0) * coalesce(v_price.input_per_million_usd,0) / 1000000.0,
    v_cached * coalesce(v_price.cached_input_per_million_usd,v_price.input_per_million_usd,0) / 1000000.0,
    (v_candidate+v_thinking) * coalesce(v_price.output_per_million_usd,0) / 1000000.0,
    coalesce(p_usage_metadata,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb)
  )
  on conflict (request_id) where request_id is not null do update set
    status=excluded.status, latency_ms=excluded.latency_ms, usage_metadata=excluded.usage_metadata,
    prompt_tokens=excluded.prompt_tokens,cached_tokens=excluded.cached_tokens,candidate_tokens=excluded.candidate_tokens,
    thinking_tokens=excluded.thinking_tokens,total_tokens=excluded.total_tokens,
    input_cost_usd=excluded.input_cost_usd,cached_input_cost_usd=excluded.cached_input_cost_usd,output_cost_usd=excluded.output_cost_usd,
    metadata=excluded.metadata
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.record_ai_usage(text,uuid,text,text,text,text,text,integer,jsonb,jsonb) from public, anon, authenticated;
grant execute on function public.record_ai_usage(text,uuid,text,text,text,text,text,integer,jsonb,jsonb) to service_role;

create or replace view public.ai_cost_daily as
select date_trunc('day',occurred_at) as day, purpose, model,
       count(*) as calls,
       sum(prompt_tokens) as prompt_tokens,
       sum(cached_tokens) as cached_tokens,
       sum(candidate_tokens) as candidate_tokens,
       sum(thinking_tokens) as thinking_tokens,
       sum(estimated_cost_usd) as estimated_cost_usd,
       avg(estimated_cost_usd) as avg_cost_per_call_usd,
       avg(latency_ms) as avg_latency_ms
from public.ai_usage_ledger
group by 1,2,3;
revoke all on public.ai_cost_daily from anon, authenticated;

create or replace view public.ai_cost_operation_unit_economics as
select model,
       count(*) filter (where purpose='operation_analysis' and status='completed') as completed_analyses,
       avg(estimated_cost_usd) filter (where purpose='operation_analysis' and status='completed') as avg_cost_per_operation_usd,
       percentile_cont(0.5) within group (order by estimated_cost_usd) filter (where purpose='operation_analysis' and status='completed') as median_cost_per_operation_usd,
       percentile_cont(0.95) within group (order by estimated_cost_usd) filter (where purpose='operation_analysis' and status='completed') as p95_cost_per_operation_usd,
       sum(estimated_cost_usd) filter (where purpose='operation_analysis' and status='completed') as total_operation_analysis_cost_usd
from public.ai_usage_ledger
group by model;
revoke all on public.ai_cost_operation_unit_economics from anon, authenticated;
