-- Correct semantic scope for Yemeni personal identity prefixes.
-- 080 and 663 are NOT Alomqy-specific. They are supporting evidence for a personal/national ID
-- and may appear inside receipts from Alomqy or any other financial entity.

update public.ai_prompts
set prompt_text = replace(
      prompt_text,
      '## قواعد دلالية خاصة بالعمقي موبايل\n- في إشعارات العمقي، النص «بط» أو «بطاقة» أو «هوية» الملاصق للرقم يعني national_id. لا تصنّف هذا الرقم account_number ولا تجعله isPrimaryRoutingIdentifier=true إذا ظهر رقم حساب صريح للمستفيد.\n- البادئتان 080 و663 قرينتان قويتان لهوية/بطاقة العمقي عندما تكونان بجوار «بط» أو «بطاقة» أو «هوية». البادئة وحدها ليست قاعدة حاسمة إذا كان الحقل مسمى صراحة «رقم الحساب».\n- أرقام حسابات العمقي المالية كثيرًا ما تبدأ بـ25. اعتبر البادئة 25 قرينة مساندة فقط، ويظل اسم الحقل والسياق البصري أقوى من شكل الرقم.\n- عند وجود «إلى حساب: <اسم المستفيد> ... بط:<رقم هوية> ... رقم <رقم حساب>» استخرج للمستفيد معرفين: national_id لرقم البطاقة وaccount_number لرقم الحساب، واجعل account_number هو Primary Routing Identifier.\n- لا تنقل national_id إلى receiver account في المخرجات المطبعة. إذا لم تجد حسابًا ماليًا واضحًا مع وجود هوية فقط، ضع reviewRequired=true بدل التخمين.\n- مثال دلالي: «إلى حساب: محمد ... بط:08010076816 رقم 254073867» => national_id=08010076816 و account_number=254073867، والمعرف الأساسي للمطابقة هو 254073867.\n',
      '## قواعد دلالية للهوية الشخصية والحسابات المالية\n- النص «بط» أو «بطاقة» أو «هوية» الملاصق للرقم يعني national_id بغض النظر عن الجهة المالية التي أصدرت الإشعار. لا تصنّف هذا الرقم account_number ولا تجعله isPrimaryRoutingIdentifier=true إذا ظهر رقم حساب صريح للطرف نفسه.\n- البادئتان 080 و663 قرينتان مساندتان على أن الرقم هو هوية شخصية/بطاقة وطنية يمنية، وقد يظهر هذا الرقم في إشعار العمقي أو أي جهة مالية أخرى. لا تربط هاتين البادئتين بجهة مالية بعينها.\n- البادئة وحدها ليست قاعدة حاسمة؛ تسمية الحقل والسياق البصري أقوى. إذا كان الرقم مسمى صراحة «رقم الحساب»، تعامل معه كحساب حتى لو تشابه شكله مع نمط آخر، ما لم يوجد تعارض بصري واضح.\n- أرقام حسابات العمقي المالية كثيرًا ما تبدأ بـ25. هذه قرينة خاصة بقالب حسابات العمقي ومساندة فقط، وليست قاعدة عامة للحسابات المالية.\n- عند وجود هوية شخصية ورقم حساب للطرف نفسه، استخرج معرفين منفصلين: national_id للهوية وaccount_number للحساب، واجعل account_number هو Primary Routing Identifier.\n- لا تنقل national_id إلى receiver account في المخرجات المطبعة. إذا لم تجد حسابًا ماليًا واضحًا مع وجود هوية فقط، ضع reviewRequired=true بدل التخمين.\n- مثال: «إلى حساب: محمد ... بط:08010076816 رقم 254073867» => national_id=08010076816 و account_number=254073867، والمعرف الأساسي للمطابقة هو 254073867. نفس قاعدة national_id تنطبق لو ظهر 080/663 في إشعار صادر عن أي جهة مالية أخرى.\n'
    ),
    version = greatest(version,16) + 1,
    notes = trim(both from concat_ws(E'\n', nullif(notes,''), 'v17: 080/663 are cross-entity personal/national-ID evidence, not Alomqy identity prefixes; 25 remains Alomqy-account supporting evidence only.')),
    updated_at = now()
where prompt_key='sanad_operation_extraction_operational_v2_shadow';
