create table if not exists private.sanad_ops_watch_runs (
  id bigint generated by default as identity primary key,
  window_start timestamptz not null,
  window_end timestamptz not null,
  status text not null default 'completed',
  new_users integer not null default 0,
  newly_verified_users integer not null default 0,
  activated_new_users integer not null default 0,
  verification_expired_after_delivery integer not null default 0,
  new_operations integer not null default 0,
  failed_operations integer not null default 0,
  assistant_inbound integer not null default 0,
  assistant_unknown integer not null default 0,
  assistant_low_confidence integer not null default 0,
  support_tickets integer not null default 0,
  whatsapp_delivery_failed integer not null default 0,
  support_whatsapp text,
  findings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

revoke all on private.sanad_ops_watch_runs from public, anon, authenticated;
grant select, insert on private.sanad_ops_watch_runs to service_role;

create or replace function public.get_sanad_public_support()
returns jsonb
language sql
security definer
set search_path=''
as $$
  select jsonb_build_object(
    'support_whatsapp', support_whatsapp,
    'support_phone', support_phone,
    'support_email', support_email,
    'support_days_text', support_days_text,
    'support_hours_text', support_hours_text,
    'support_response_time_text', support_response_time_text
  )
  from public.app_public_information
  where singleton=true
  limit 1
$$;
revoke all on function public.get_sanad_public_support() from public,anon,authenticated;
grant execute on function public.get_sanad_public_support() to service_role;

create or replace function private.run_sanad_ops_watch_snapshot(
  p_window_end timestamptz default now(),
  p_window_minutes integer default 60
) returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_end timestamptz := coalesce(p_window_end, now());
  v_start timestamptz := v_end - make_interval(mins => greatest(5, least(coalesce(p_window_minutes,60),1440)));
  v_support text;
  v_new_users int := 0;
  v_verified int := 0;
  v_activated int := 0;
  v_expired_delivered int := 0;
  v_ops int := 0;
  v_failed_ops int := 0;
  v_inbound int := 0;
  v_unknown int := 0;
  v_low int := 0;
  v_tickets int := 0;
  v_delivery_failed int := 0;
  v_findings jsonb := '[]'::jsonb;
  v_id bigint;
begin
  select support_whatsapp into v_support
  from public.app_public_information
  where singleton = true
  limit 1;

  select count(*) into v_new_users from public.profiles where created_at >= v_start and created_at < v_end;
  select count(*) into v_verified from public.profiles where phone_verified_at >= v_start and phone_verified_at < v_end;

  select count(distinct p.id) into v_activated
  from public.profiles p
  join public.operation_user_links l on l.user_id = p.id
  where p.created_at >= v_start and p.created_at < v_end
    and l.created_at < v_end;

  select count(*) into v_expired_delivered
  from public.phone_verification_claims c
  where c.expires_at >= v_start and c.expires_at < v_end
    and c.status = 'expired'
    and coalesce(c.metadata->>'whatsapp_delivery_status','') in ('delivered','read');

  select count(*) into v_ops from public.operations where created_at >= v_start and created_at < v_end;
  select count(*) into v_failed_ops from public.operations where created_at >= v_start and created_at < v_end and (status='failed' or ai_status='failed' or nullif(ai_error,'') is not null);

  select count(*) into v_inbound from public.sanad_assistant_messages where direction='inbound' and created_at >= v_start and created_at < v_end;
  select count(*) into v_unknown from public.sanad_assistant_messages where direction='inbound' and created_at >= v_start and created_at < v_end and intent='unknown';
  select count(*) into v_low from public.sanad_assistant_messages where direction='inbound' and created_at >= v_start and created_at < v_end and coalesce(confidence,0) < 0.60;
  select count(*) into v_tickets from public.sanad_assistant_support_tickets where created_at >= v_start and created_at < v_end;

  select
    (select count(*) from public.phone_verification_events where occurred_at >= v_start and occurred_at < v_end and event_type='whatsapp_failed')
    + (select count(*) from public.sanad_transactional_message_outbox where failed_at >= v_start and failed_at < v_end)
    + (select count(*) from public.sanad_assistant_media_deliveries where failed_at >= v_start and failed_at < v_end)
  into v_delivery_failed;

  select coalesce(jsonb_agg(finding order by occurred_at), '[]'::jsonb) into v_findings
  from (
    select c.expires_at as occurred_at,
      jsonb_build_object('kind','verification_expired_after_delivery','severity','warning','user_id',c.user_id,'claim_id',c.id,'delivery_status',c.metadata->>'whatsapp_delivery_status','expires_at',c.expires_at) finding
    from public.phone_verification_claims c
    where c.expires_at >= v_start and c.expires_at < v_end
      and c.status='expired'
      and coalesce(c.metadata->>'whatsapp_delivery_status','') in ('delivered','read')
    union all
    select m.created_at,
      jsonb_build_object('kind','assistant_unknown','severity','warning','message_id',m.id,'conversation_id',m.conversation_id,'contact_id',m.contact_id,'confidence',m.confidence,'text',left(coalesce(m.body_text,m.transcript,''),240))
    from public.sanad_assistant_messages m
    where m.direction='inbound' and m.created_at >= v_start and m.created_at < v_end and m.intent='unknown'
    union all
    select m.created_at,
      jsonb_build_object('kind','assistant_low_confidence','severity','warning','message_id',m.id,'conversation_id',m.conversation_id,'contact_id',m.contact_id,'intent',m.intent,'confidence',m.confidence,'text',left(coalesce(m.body_text,m.transcript,''),240))
    from public.sanad_assistant_messages m
    where m.direction='inbound' and m.created_at >= v_start and m.created_at < v_end and m.intent<>'unknown' and coalesce(m.confidence,0) < 0.60
    union all
    select o.created_at,
      jsonb_build_object('kind','operation_failed','severity','error','operation_id',o.id,'pipeline_run_id',o.pipeline_run_id,'status',o.status,'ai_status',o.ai_status,'error',left(coalesce(o.ai_error,''),500))
    from public.operations o
    where o.created_at >= v_start and o.created_at < v_end and (o.status='failed' or o.ai_status='failed' or nullif(o.ai_error,'') is not null)
    union all
    select m.created_at,
      jsonb_build_object('kind','support_referral_missing_official_number','severity','error','message_id',m.id,'conversation_id',m.conversation_id,'official_support_whatsapp',v_support)
    from public.sanad_assistant_messages m
    where m.direction='outbound' and m.created_at >= v_start and m.created_at < v_end and m.intent='human_support'
      and nullif(v_support,'') is not null
      and coalesce(m.body_text,'') not like '%'||v_support||'%'
  ) q;

  insert into private.sanad_ops_watch_runs(
    window_start,window_end,new_users,newly_verified_users,activated_new_users,
    verification_expired_after_delivery,new_operations,failed_operations,
    assistant_inbound,assistant_unknown,assistant_low_confidence,support_tickets,
    whatsapp_delivery_failed,support_whatsapp,findings
  ) values (
    v_start,v_end,v_new_users,v_verified,v_activated,v_expired_delivered,v_ops,v_failed_ops,
    v_inbound,v_unknown,v_low,v_tickets,v_delivery_failed,v_support,v_findings
  ) returning id into v_id;

  return v_id;
end;
$$;
revoke all on function private.run_sanad_ops_watch_snapshot(timestamptz,integer) from public, anon, authenticated;
grant execute on function private.run_sanad_ops_watch_snapshot(timestamptz,integer) to service_role;

create or replace function public.get_sanad_ops_watch_latest()
returns jsonb
language sql
security definer
set search_path = ''
as $$
  select to_jsonb(r) from private.sanad_ops_watch_runs r order by r.id desc limit 1
$$;
revoke all on function public.get_sanad_ops_watch_latest() from public, anon, authenticated;
grant execute on function public.get_sanad_ops_watch_latest() to service_role;

do $$
declare v_jobid bigint;
begin
  select jobid into v_jobid from cron.job where jobname='sanad_ops_watch_hourly' limit 1;
  if v_jobid is not null then perform cron.unschedule(v_jobid); end if;
  perform cron.schedule('sanad_ops_watch_hourly','0 * * * *',$cron$select private.run_sanad_ops_watch_snapshot(now(),60);$cron$);
end $$;