-- SANAD ERP logical cloud replica v1
-- Adds periodic full logical snapshots without changing the proven minute-level sale path.
-- This is a logical data copy, not a SQL Server .bak / physical disaster-recovery backup.

alter table public.business_erp_baseline_runs
  drop constraint if exists business_erp_baseline_runs_baseline_kind_check;

alter table public.business_erp_baseline_runs
  add constraint business_erp_baseline_runs_baseline_kind_check
  check (baseline_kind in ('initial','reconciliation','logical_backup'));

create table if not exists public.business_erp_snapshot_rows (
  id bigint generated by default as identity primary key,
  snapshot_public_id uuid not null,
  business_id uuid not null references public.business_profiles(id) on delete cascade,
  source_instance_id uuid not null references public.business_erp_source_instances(id) on delete cascade,
  table_name text not null,
  row_key text not null,
  row_hash text not null,
  row_data jsonb not null,
  captured_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (snapshot_public_id, table_name, row_key)
);

create index if not exists business_erp_snapshot_rows_business_idx
  on public.business_erp_snapshot_rows(business_id, snapshot_public_id, table_name);
create index if not exists business_erp_snapshot_rows_source_idx
  on public.business_erp_snapshot_rows(source_instance_id, snapshot_public_id, table_name);
create index if not exists business_erp_snapshot_rows_row_hash_idx
  on public.business_erp_snapshot_rows(snapshot_public_id, table_name, row_hash);

alter table public.business_erp_snapshot_rows enable row level security;

drop policy if exists business_erp_snapshot_rows_member_select on public.business_erp_snapshot_rows;
create policy business_erp_snapshot_rows_member_select
on public.business_erp_snapshot_rows
for select to authenticated
using (
  private.user_is_business_owner(business_id, (select auth.uid()))
  or private.user_is_active_business_member(business_id, (select auth.uid()))
);

revoke all on table public.business_erp_snapshot_rows from anon;
grant select on table public.business_erp_snapshot_rows to authenticated;
grant select, insert, update, delete on table public.business_erp_snapshot_rows to service_role;

create or replace function public.apply_erp_logical_snapshot_chunk_v1(p_raw_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_raw public.business_erp_raw_events%rowtype;
  v_run public.business_erp_baseline_runs%rowtype;
  v_snapshot_id uuid;
  v_table_name text;
  v_rows jsonb;
  v_inserted integer := 0;
begin
  select * into v_raw
  from public.business_erp_raw_events
  where id = p_raw_event_id
  for update;

  if not found then
    raise exception 'raw_event_not_found' using errcode = '22023';
  end if;

  if v_raw.entity_type <> 'erp_logical_snapshot_chunk' then
    raise exception 'invalid_snapshot_entity_type' using errcode = '22023';
  end if;

  begin
    v_snapshot_id := nullif(v_raw.payload->>'snapshot_public_id','')::uuid;
  exception when others then
    raise exception 'invalid_snapshot_public_id' using errcode = '22023';
  end;

  v_table_name := nullif(btrim(coalesce(v_raw.payload->>'table_name','')), '');
  v_rows := coalesce(v_raw.payload->'rows', '[]'::jsonb);

  if v_snapshot_id is null or v_table_name is null or jsonb_typeof(v_rows) <> 'array' then
    raise exception 'invalid_snapshot_chunk' using errcode = '22023';
  end if;

  select * into v_run
  from public.business_erp_baseline_runs
  where baseline_public_id = v_snapshot_id
    and source_instance_id = v_raw.source_instance_id
    and business_id = v_raw.business_id
    and baseline_kind = 'logical_backup'
    and status in ('started','uploading','completed')
  limit 1;

  if not found then
    raise exception 'snapshot_run_not_found' using errcode = '22023';
  end if;

  insert into public.business_erp_snapshot_rows (
    snapshot_public_id,
    business_id,
    source_instance_id,
    table_name,
    row_key,
    row_hash,
    row_data,
    captured_at
  )
  select
    v_snapshot_id,
    v_raw.business_id,
    v_raw.source_instance_id,
    v_table_name,
    nullif(btrim(item->>'row_key'),''),
    nullif(btrim(item->>'row_hash'),''),
    coalesce(item->'data','{}'::jsonb),
    v_raw.captured_at
  from jsonb_array_elements(v_rows) item
  where nullif(btrim(item->>'row_key'),'') is not null
    and nullif(btrim(item->>'row_hash'),'') is not null
  on conflict (snapshot_public_id, table_name, row_key)
  do update set
    row_hash = excluded.row_hash,
    row_data = excluded.row_data,
    captured_at = excluded.captured_at;

  get diagnostics v_inserted = row_count;

  update public.business_erp_raw_events
  set normalization_status = 'normalized',
      normalized_at = now(),
      normalization_error = null
  where id = v_raw.id;

  update public.business_erp_baseline_runs
  set status = case when status='started' then 'uploading' else status end,
      last_seen_at = now()
  where id = v_run.id;

  return jsonb_build_object(
    'status','normalized',
    'snapshot_public_id',v_snapshot_id,
    'table_name',v_table_name,
    'rows_applied',v_inserted,
    'contract_version',1
  );
end;
$function$;

revoke all on function public.apply_erp_logical_snapshot_chunk_v1(uuid) from public, anon, authenticated;
grant execute on function public.apply_erp_logical_snapshot_chunk_v1(uuid) to service_role;

create or replace function public.start_erp_baseline_v1(
  p_device_public_id uuid,
  p_baseline_public_id uuid,
  p_baseline_kind text,
  p_adapter_code text,
  p_adapter_version text,
  p_schema_fingerprint text,
  p_manifest jsonb,
  p_expected_counts jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_device public.business_bridge_devices%rowtype;
  v_source public.business_erp_source_instances%rowtype;
  v_existing public.business_erp_baseline_runs%rowtype;
  v_run_id uuid;
  v_kind text := coalesce(nullif(btrim(p_baseline_kind),''),'initial');
begin
  if p_device_public_id is null
     or p_baseline_public_id is null
     or nullif(btrim(p_adapter_code), '') is null
     or nullif(btrim(p_adapter_version), '') is null
     or nullif(btrim(p_schema_fingerprint), '') is null then
    raise exception 'invalid_baseline_request' using errcode = '22023';
  end if;

  if v_kind not in ('initial','reconciliation','logical_backup') then
    raise exception 'invalid_baseline_kind' using errcode = '22023';
  end if;

  if jsonb_typeof(coalesce(p_manifest, '{}'::jsonb)) <> 'object'
     or jsonb_typeof(coalesce(p_expected_counts, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid_baseline_manifest' using errcode = '22023';
  end if;

  select d.* into v_device
  from public.business_bridge_devices d
  join public.business_accounting_connections c on c.id = d.connection_id
  where d.device_public_id = p_device_public_id
    and d.status = 'active'
    and c.status in ('pending','connected','error')
  limit 1;

  if not found then
    raise exception 'bridge_device_not_active' using errcode = '42501';
  end if;

  select s.* into v_source
  from public.business_erp_source_instances s
  where s.id = v_device.source_instance_id
  for update;

  if not found or v_source.status not in ('active','changed') then
    raise exception 'erp_source_not_active' using errcode = '42501';
  end if;

  -- The registered/core fingerprint remains the compatibility guard.
  -- The full logical snapshot fingerprint is carried separately in manifest.full_schema_fingerprint.
  if v_source.schema_fingerprint is not null
     and v_source.schema_fingerprint <> btrim(p_schema_fingerprint) then
    update public.business_erp_source_instances
    set status = 'changed', last_seen_at = now(),
        metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
          'last_observed_schema_fingerprint', btrim(p_schema_fingerprint),
          'schema_changed_at', now()
        )
    where id = v_source.id;

    update public.business_accounting_connections
    set status = 'error', last_error_code = 'schema_fingerprint_mismatch', last_error_at = now()
    where id = v_device.connection_id;

    raise exception 'schema_fingerprint_mismatch' using errcode = '22023';
  end if;

  if v_source.schema_fingerprint is null then
    update public.business_erp_source_instances
    set schema_fingerprint = btrim(p_schema_fingerprint), status = 'active', last_seen_at = now()
    where id = v_source.id;
  else
    update public.business_erp_source_instances set last_seen_at = now() where id = v_source.id;
  end if;

  select * into v_existing
  from public.business_erp_baseline_runs
  where baseline_public_id = p_baseline_public_id
  limit 1;

  if found then
    if v_existing.source_instance_id <> v_device.source_instance_id
       or v_existing.bridge_device_id <> v_device.id
       or v_existing.schema_fingerprint <> btrim(p_schema_fingerprint)
       or v_existing.baseline_kind <> v_kind then
      raise exception 'baseline_id_conflict' using errcode = '23505';
    end if;

    update public.business_erp_baseline_runs set last_seen_at = now() where id = v_existing.id;

    return jsonb_build_object(
      'status', v_existing.status,
      'baseline_public_id', v_existing.baseline_public_id,
      'started_at', v_existing.started_at,
      'completed_at', v_existing.completed_at,
      'contract_version', 1
    );
  end if;

  insert into public.business_erp_baseline_runs (
    baseline_public_id,business_id,location_id,connection_id,source_instance_id,bridge_device_id,
    baseline_kind,adapter_code,adapter_version,schema_fingerprint,status,manifest,expected_counts
  ) values (
    p_baseline_public_id,v_device.business_id,v_device.location_id,v_device.connection_id,
    v_device.source_instance_id,v_device.id,v_kind,btrim(p_adapter_code),btrim(p_adapter_version),
    btrim(p_schema_fingerprint),'started',coalesce(p_manifest,'{}'::jsonb),coalesce(p_expected_counts,'{}'::jsonb)
  ) returning id into v_run_id;

  update public.business_accounting_connections
  set status = case when status='connected' then status else 'pending' end,
      last_heartbeat_at = now(), adapter_version = btrim(p_adapter_version),
      last_error_code = null, last_error_at = null
  where id = v_device.connection_id;

  update public.business_bridge_devices
  set last_heartbeat_at = now(), adapter_version = btrim(p_adapter_version)
  where id = v_device.id;

  return jsonb_build_object(
    'status','started',
    'baseline_public_id',p_baseline_public_id,
    'run_id',v_run_id,
    'started_at',now(),
    'contract_version',1
  );
end;
$function$;

create or replace function public.complete_erp_baseline_v1(
  p_device_public_id uuid,
  p_baseline_public_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_device public.business_bridge_devices%rowtype;
  v_run public.business_erp_baseline_runs%rowtype;
  v_received jsonb := '{}'::jsonb;
  v_key text;
  v_expected integer;
  v_actual integer;
  v_entity_type text;
begin
  select * into v_device
  from public.business_bridge_devices
  where device_public_id = p_device_public_id and status='active'
  limit 1;
  if not found then raise exception 'bridge_device_not_active' using errcode='42501'; end if;

  select * into v_run
  from public.business_erp_baseline_runs
  where baseline_public_id = p_baseline_public_id and bridge_device_id = v_device.id
  for update;
  if not found then raise exception 'baseline_run_not_found' using errcode='22023'; end if;

  if v_run.status='completed' then
    return jsonb_build_object(
      'status','completed',
      'baseline_public_id',v_run.baseline_public_id,
      'received_counts',v_run.received_counts,
      'completed_at',v_run.completed_at,
      'contract_version',1
    );
  end if;

  if v_run.status not in ('started','uploading') then
    raise exception 'baseline_run_not_completable' using errcode='22023';
  end if;

  if v_run.baseline_kind='logical_backup' then
    v_entity_type := 'erp_logical_snapshot_chunk';

    select coalesce(jsonb_object_agg(x.table_name,x.row_count),'{}'::jsonb)
    into v_received
    from (
      select
        e.integrity->>'table_name' as table_name,
        sum(case when coalesce(e.integrity->>'row_count','') ~ '^[0-9]+$'
                 then (e.integrity->>'row_count')::integer else 0 end)::integer as row_count
      from public.business_erp_raw_events e
      where e.source_instance_id = v_run.source_instance_id
        and e.entity_type = v_entity_type
        and e.integrity->>'baseline_public_id' = p_baseline_public_id::text
        and e.integrity->>'schema_fingerprint' = v_run.schema_fingerprint
      group by e.integrity->>'table_name'
    ) x
    where x.table_name is not null;
  else
    v_entity_type := 'erp_master_snapshot';

    select coalesce(jsonb_object_agg(x.source_record_id,x.row_count),'{}'::jsonb)
    into v_received
    from (
      select distinct on (e.source_record_id)
        e.source_record_id,
        case when coalesce(e.integrity->>'row_count','') ~ '^[0-9]+$'
             then (e.integrity->>'row_count')::integer else -1 end as row_count
      from public.business_erp_raw_events e
      where e.source_instance_id = v_run.source_instance_id
        and e.entity_type = v_entity_type
        and e.integrity->>'baseline_public_id' = p_baseline_public_id::text
        and e.integrity->>'schema_fingerprint' = v_run.schema_fingerprint
      order by e.source_record_id,e.received_at desc
    ) x;
  end if;

  for v_key in select key from jsonb_each_text(v_run.expected_counts)
  loop
    begin
      v_expected := (v_run.expected_counts->>v_key)::integer;
    exception when others then
      raise exception 'invalid_expected_count:%',v_key using errcode='22023';
    end;

    if not (v_received ? v_key) then
      raise exception 'baseline_snapshot_missing:%',v_key using errcode='22023';
    end if;

    v_actual := (v_received->>v_key)::integer;
    if v_actual <> v_expected then
      raise exception 'baseline_snapshot_count_mismatch:%',v_key using errcode='22023';
    end if;
  end loop;

  update public.business_erp_baseline_runs
  set status='completed',received_counts=v_received,completed_at=now(),last_seen_at=now(),
      error_code=null,error_detail=null
  where id=v_run.id;

  if v_run.baseline_kind <> 'logical_backup' then
    update public.business_erp_raw_events
    set normalization_status='warning',normalized_at=now(),
        normalization_error='baseline_snapshot_mapping_pending'
    where source_instance_id=v_run.source_instance_id
      and entity_type='erp_master_snapshot'
      and integrity->>'baseline_public_id'=p_baseline_public_id::text
      and normalization_status='pending';
  end if;

  update public.business_accounting_connections
  set status='connected',last_sync_at=now(),last_heartbeat_at=now(),
      last_error_code=null,last_error_at=null,
      metadata=coalesce(metadata,'{}'::jsonb) || case
        when v_run.baseline_kind='logical_backup'
        then jsonb_build_object(
          'last_logical_backup_at',now(),
          'last_logical_backup_id',p_baseline_public_id,
          'logical_backup_kind','full_table_snapshot'
        )
        else '{}'::jsonb
      end
  where id=v_run.connection_id;

  update public.business_erp_source_instances set status='active',last_seen_at=now()
  where id=v_run.source_instance_id;
  update public.business_bridge_devices set last_heartbeat_at=now()
  where id=v_run.bridge_device_id;

  return jsonb_build_object(
    'status','completed',
    'baseline_kind',v_run.baseline_kind,
    'baseline_public_id',p_baseline_public_id,
    'received_counts',v_received,
    'completed_at',now(),
    'contract_version',1
  );
end;
$function$;

revoke all on function public.start_erp_baseline_v1(uuid,uuid,text,text,text,text,jsonb,jsonb) from public, anon, authenticated;
grant execute on function public.start_erp_baseline_v1(uuid,uuid,text,text,text,text,jsonb,jsonb) to service_role;
revoke all on function public.complete_erp_baseline_v1(uuid,uuid) from public, anon, authenticated;
grant execute on function public.complete_erp_baseline_v1(uuid,uuid) to service_role;

create or replace function public.get_business_erp_snapshot_status_v1(p_business_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_uid uuid := auth.uid();
  v_latest public.business_erp_baseline_runs%rowtype;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if not (
    private.user_is_business_owner(p_business_id,v_uid)
    or private.user_is_active_business_member(p_business_id,v_uid)
  ) then
    raise exception 'business_access_denied' using errcode='42501';
  end if;

  select * into v_latest
  from public.business_erp_baseline_runs
  where business_id=p_business_id
    and baseline_kind='logical_backup'
  order by started_at desc
  limit 1;

  if not found then
    return jsonb_build_object(
      'available',false,
      'snapshot_public_id',null,
      'status','not_started',
      'contract_version',1
    );
  end if;

  return jsonb_build_object(
    'available',v_latest.status='completed',
    'snapshot_public_id',v_latest.baseline_public_id,
    'status',v_latest.status,
    'started_at',v_latest.started_at,
    'completed_at',v_latest.completed_at,
    'expected_counts',v_latest.expected_counts,
    'received_counts',v_latest.received_counts,
    'manifest',v_latest.manifest,
    'contract_version',1
  );
end;
$function$;

revoke all on function public.get_business_erp_snapshot_status_v1(uuid) from public,anon;
grant execute on function public.get_business_erp_snapshot_status_v1(uuid) to authenticated;

create or replace function public.get_business_erp_snapshot_table_rows_v1(
  p_business_id uuid,
  p_table_name text,
  p_limit integer default 200,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_uid uuid := auth.uid();
  v_snapshot uuid;
  v_limit integer := least(greatest(coalesce(p_limit,200),1),1000);
  v_offset integer := greatest(coalesce(p_offset,0),0);
  v_items jsonb;
  v_total bigint;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  if nullif(btrim(p_table_name),'') is null then raise exception 'table_name_required' using errcode='22023'; end if;

  if not (
    private.user_is_business_owner(p_business_id,v_uid)
    or private.user_is_active_business_member(p_business_id,v_uid)
  ) then
    raise exception 'business_access_denied' using errcode='42501';
  end if;

  select baseline_public_id into v_snapshot
  from public.business_erp_baseline_runs
  where business_id=p_business_id
    and baseline_kind='logical_backup'
    and status='completed'
  order by completed_at desc
  limit 1;

  if v_snapshot is null then
    return jsonb_build_object('items','[]'::jsonb,'total',0,'snapshot_public_id',null,'contract_version',1);
  end if;

  select count(*) into v_total
  from public.business_erp_snapshot_rows
  where business_id=p_business_id and snapshot_public_id=v_snapshot and table_name=btrim(p_table_name);

  select coalesce(jsonb_agg(to_jsonb(x) order by x.row_key),'[]'::jsonb)
  into v_items
  from (
    select row_key,row_hash,row_data,captured_at
    from public.business_erp_snapshot_rows
    where business_id=p_business_id
      and snapshot_public_id=v_snapshot
      and table_name=btrim(p_table_name)
    order by row_key
    limit v_limit offset v_offset
  ) x;

  return jsonb_build_object(
    'items',v_items,
    'total',v_total,
    'limit',v_limit,
    'offset',v_offset,
    'snapshot_public_id',v_snapshot,
    'table_name',btrim(p_table_name),
    'contract_version',1
  );
end;
$function$;

revoke all on function public.get_business_erp_snapshot_table_rows_v1(uuid,text,integer,integer) from public,anon;
grant execute on function public.get_business_erp_snapshot_table_rows_v1(uuid,text,integer,integer) to authenticated;
